### ISSUE TITLE
[Bug] PostgreSQL null value of uuid column cannot bind to Type.VARCHAR

### ISSUE THREAD

**Issue by ArgonarioD** [babyfish-ct/jimmer#184]
当使用PostgreSQL时，将UUID类型的字段设置为null后进行数据库交互会导致如下异常：
```
org.babyfish.jimmer.sql.runtime.ExecutionException: Cannot execute SQL statement: insert into knowledge(id, name, create_time, parent_id) values(?, ?, ?, ?), variables: [2c9b82c8-508a-49d1-8989-c0ffdeeafe5a, 南联被已通的, 2023-06-30T02:31:32.457885, DbNull{type=class java.util.UUID}]
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:43) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.simpleLog(ExecutorForLog.java:102) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.execute(ExecutorForLog.java:42) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.insert(Saver.java:589) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:436) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveImpl(Saver.java:112) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:93) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:158) ~[jimmer-core-0.7.104.jar:?]
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42) ~[jimmer-core-0.7.104.jar:?]
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:92) ~[jimmer-core-0.7.104.jar:?]
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39) ~[jimmer-core-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:89) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:63) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.SpringConnectionManager.execute(SpringConnectionManager.java:22) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:57) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:11) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.save(KEntitiesImpl.kt:138) ~[jimmer-sql-kotlin-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.kt.KEntities$DefaultImpls.save$default(KEntities.kt:49) ~[jimmer-sql-kotlin-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.support.KRepositoryImpl.save(KRepositoryImpl.kt:134) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.KRepository$DefaultImpls.save(KRepository.kt:110) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.support.KRepositoryImpl.save(KRepositoryImpl.kt:20) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.KRepository$DefaultImpls.save(KRepository.kt:104) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at org.babyfish.jimmer.spring.repository.support.KRepositoryImpl.save(KRepositoryImpl.kt:20) ~[jimmer-spring-boot-starter-0.7.104.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223) ~[spring-aop-6.0.9.jar:6.0.9]
       ...
Caused by: org.postgresql.util.PSQLException: ERROR: column "parent_id" is of type uuid but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：76
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152) ~[postgresql-42.6.0.jar:42.6.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:?]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$insert$5(Saver.java:611) ~[jimmer-sql-0.7.104.jar:?]
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:41) ~[jimmer-sql-0.7.104.jar:?]
	... 126 more
```

**Comment by babyfish-ct** [comment]
This is not bug, in this cause(map varchar to uuid), you should use property-level scalar provider
