### ISSUE TITLE
定义抽象方法countByColumnNameIn报错

### ISSUE THREAD

**Issue by zxzf1234** [babyfish-ct/jimmer#189]
Caused by: java.lang.IllegalArgumentException: Illegal abstract spring-data method "public abstract java.lang.Long cn.iocoder.yudao.service.repository.infra.codegen.InfraDatabaseColumnRepository.countByColumnNameIn(java.util.List)": The return type must be boolean
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:74)
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:66)
	at org.babyfish.jimmer.spring.repository.parser.QueryMethod.of(QueryMethod.java:34)
	at org.babyfish.jimmer.spring.repository.bytecode.MethodCodeWriter.write(MethodCodeWriter.java:38)
	at org.babyfish.jimmer.spring.repository.bytecode.ClassCodeWriter.write(ClassCodeWriter.java:113)
	at org.babyfish.jimmer.spring.repository.support.JimmerRepositoryFactory.getTargetRepository(JimmerRepositoryFactory.java:100)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:325)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:231)
	at org.springframework.data.util.Lazy.get(Lazy.java:115)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 62 common frames omitted

**Comment by babyfish-ct** [comment]
Cannot be reproduced.

I got the exception message 'must be int or long', count is not nullable, so it must be int/Long, not Integer/Long.

Try the newest version please.

**Comment by zxzf1234** [comment]
已验证修复
