### ISSUE TITLE
启用缓存后某些情况下报错

### ISSUE THREAD

**Issue by llh4github** [babyfish-ct/jimmer#225]
报错信息：
```
java.lang.NullPointerException: Cannot invoke "org.babyfish.jimmer.runtime.ImmutableSpi.__isLoaded(org.babyfish.jimmer.meta.PropId)" because "spi" is null
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:283) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:208) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:150) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.loader.AbstractDataLoader.findTargets(AbstractDataLoader.java:782) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.loader.AbstractDataLoader.loadParents(AbstractDataLoader.java:337) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.loader.AbstractDataLoader.load(AbstractDataLoader.java:200) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.FetcherTask.execute(FetcherTask.java:103) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.FetcherContext.execute(FetcherContext.java:95) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.Fetchers.lambda$fetch$1(Fetchers.java:109) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.FetcherContext.using(FetcherContext.java:41) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.Fetchers.fetch(Fetchers.java:106) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.Fetchers.lambda$fetch$0(Fetchers.java:66) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:158) ~[jimmer-core-0.8.0.jar:na]
	at org.babyfish.jimmer.runtime.Internal.lambda$produceList$2(Internal.java:64) ~[jimmer-core-0.8.0.jar:na]
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:92) ~[jimmer-core-0.8.0.jar:na]
	at org.babyfish.jimmer.runtime.Internal.produceList(Internal.java:55) ~[jimmer-core-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.fetcher.impl.Fetchers.fetch(Fetchers.java:62) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.runtime.Selectors.select(Selectors.java:56) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:180) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.spring.repository.SpringConnectionManager.execute(SpringConnectionManager.java:22) ~[jimmer-spring-boot-starter-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:170) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:24) ~[jimmer-sql-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.kt.ast.query.impl.KTypedRootQueryImpl.execute(KTypedRootQueryImpl.kt:27) ~[jimmer-sql-kotlin-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.kt.ast.query.impl.KTypedRootQueryImpl.execute(KTypedRootQueryImpl.kt:7) ~[jimmer-sql-kotlin-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.kt.ast.query.KConfigurableRootQueriesKt.fetchPage(KConfigurableRootQueries.kt:66) ~[jimmer-sql-kotlin-0.8.0.jar:na]
	at org.babyfish.jimmer.sql.kt.ast.query.KConfigurableRootQueriesKt.fetchPage$default(KConfigurableRootQueries.kt:7) ~[jimmer-sql-kotlin-0.8.0.jar:na]
	at io.github.llh4github.kinoapi.service.BaseKt.pageQuery(base.kt:37) ~[main/:na]
	at io.github.llh4github.kinoapi.service.auth.impl.RoleServiceImpl.pageQuery(RoleServiceImpl.kt:41) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.11.jar:6.0.11]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-6.0.11.jar:6.0.11]
	at io.github.llh4github.kinoapi.service.auth.impl.RoleServiceImpl$$SpringCGLIB$$0.pageQuery(<generated>) ~[main/:na]
	at io.github.llh4github.kinoapi.api.auth.RoleApi.page(RoleApi.kt:36) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.11.jar:6.0.11]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by babyfish-ct** [comment]
Try `0.8.3`
