### ISSUE TITLE
当使用QBE查询时，定义的查询实体所有字段均为null(前端参数均不传) 执行查询报错

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#247]
# 问题描述
当demo中的AuthorSpecification：https://github.com/babyfish-ct/jimmer/blob/main/example/java/jimmer-sql/src/main/dto/org/babyfish/jimmer/sql/example/model/Author.dto

在接口中所有字段都不传递  均为null时，执行查询报错：java.lang.NullPointerException: null cannot be cast to non-null type org.babyfish.jimmer.sql.ast.impl.PredicateImplementor

demo 接口：org.babyfish.jimmer.sql.example.business.AuthorService#findAuthors
 curl：

```bash
curl -X "GET" "http://localhost:8080/author/list" \

```
这里要注意：AuthorSpecification参数实体 不传递任何字段值
此时接收到的对象:
<img width="1030" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/32fbfa15-5735-4591-8793-bc2f5be6fb1b">

AuthorSpecification实体转换entity 为全空

<img width="458" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/9bf27f30-49d7-4964-875b-441c471439e6">

执行查询：

<img width="505" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/1b5f1501-ad73-44e6-988c-e39aa278f5e8">

最终报错：

```bash
java.lang.NullPointerException: null cannot be cast to non-null type org.babyfish.jimmer.sql.ast.impl.PredicateImplementor
	at org.babyfish.jimmer.sql.kt.ast.expression.KExpressionsKt.eq(KExpressions.kt:130) ~[jimmer-sql-kotlin-0.8.12.jar:na]
	at org.babyfish.jimmer.sql.example.repository.AuthorRepository$find$1.invoke(AuthorRepository.kt:25) ~[main/:na]
	at org.babyfish.jimmer.sql.example.repository.AuthorRepository$find$1.invoke(AuthorRepository.kt:23) ~[main/:na]
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.createQuery(KSqlClientImpl.kt:50) ~[jimmer-sql-kotlin-0.8.12.jar:na]
	at org.babyfish.jimmer.sql.example.repository.AuthorRepository$DefaultImpls.find(AuthorRepository.kt:23) ~[main/:na]
	at org.babyfish.jimmer.sql.example.repository.AuthorRepository{AsmImpl}.find(Unknown Source) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]


```

**Comment by babyfish-ct** [comment]
Try `0.8.13`

**Comment by qinkangdeid** [comment]
升级0.8.13解决🌺
