### ISSUE TITLE
[Feature Request]针对过滤器关联属性的可空校验建议提供开关

### ISSUE THREAD

**Issue by zqsemax07** [babyfish-ct/jimmer#248]
<img width="800" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/117254035/f71ac477-3cc0-4812-93a2-ea32f5e96b18">

现有的`ManyToOne`注解中的`inputNonNull`参数，只是保证插入库中的属性不为空，还是需要将entity中的属性设置为可空，对应的dto也是可空的，与实际业务有一定出入，需要进行针对性的调整。

对多租户等场景，实际业务是可以保证过滤器不会导致子表被过滤为空的，这种情况下建议允许用户跳过这段校验。

**Comment by babyfish-ct** [comment]
Try `0.8.13`

**Comment by JackyLeeCS** [comment]
> Try `0.8.13`

要怎么配置跳过校验呢

**Comment by babyfish-ct** [comment]
不用，智能的。

只有关联对象具备当前对象没有的过滤器，才会要求null.

多租户过滤器，双方都有，比了一个寂寞，所以，不必为null

**Comment by JackyLeeCS** [comment]
`0.8.16`版本，实现`KAssociationIntegrityAssuranceFilter`后报了空指针异常

```log
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlClient' defined in class path resource [org/babyfish/jimmer/spring/cfg/SqlClientConfig.class]: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: Cannot read the array length because "args" is null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: Cannot read the array length because "args" is null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 33 common frames omitted
Caused by: java.lang.NullPointerException: Cannot read the array length because "args" is null
	at org.babyfish.jimmer.sql.kt.filter.impl.JavaFiltersKt.toJavaFilter$lambda-0(JavaFilters.kt:41)
	at jdk.proxy2/jdk.proxy2.$Proxy138.hashCode(Unknown Source)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.standardFilters(FilterManager.java:459)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.<init>(FilterManager.java:61)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.createFilterManager(JSqlClientImpl.java:1324)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.build(JSqlClientImpl.java:1211)
	at org.babyfish.jimmer.sql.kt.cfg.KSqlClientDsl.buildKSqlClient$jimmer_sql_kotlin(KSqlClientDsl.kt:381)
	at org.babyfish.jimmer.sql.kt.KSqlClientKt.newKSqlClient(KSqlClient.kt:167)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig.kotlinSqlClient(SqlClientConfig.java:171)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.CGLIB$kotlinSqlClient$1(<generated>)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.kotlinSqlClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 34 common frames omitted
```

**Comment by babyfish-ct** [comment]
Try `0.8.17`

**Comment by JackyLeeCS** [comment]
换了个错误
```kotlin
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlClient' defined in class path resource [org/babyfish/jimmer/spring/cfg/SqlClientConfig.class]: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: wrong number of arguments
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: wrong number of arguments
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.babyfish.jimmer.sql.kt.filter.impl.JavaFiltersKt.toJavaFilter$lambda-0(JavaFilters.kt:41)
	at jdk.proxy2/jdk.proxy2.$Proxy138.hashCode(Unknown Source)
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.standardFilters(FilterManager.java:459)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.<init>(FilterManager.java:61)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.createFilterManager(JSqlClientImpl.java:1324)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.build(JSqlClientImpl.java:1211)
	at org.babyfish.jimmer.sql.kt.cfg.KSqlClientDsl.buildKSqlClient$jimmer_sql_kotlin(KSqlClientDsl.kt:381)
	at org.babyfish.jimmer.sql.kt.KSqlClientKt.newKSqlClient(KSqlClient.kt:167)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig.kotlinSqlClient(SqlClientConfig.java:171)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.CGLIB$kotlinSqlClient$1(<generated>)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.kotlinSqlClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 34 common frames omitted
```

**Comment by babyfish-ct** [comment]
Try `0.8.18`

**Comment by JackyLeeCS** [comment]
报错了
```kotlin
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlClient' defined in class path resource [org/babyfish/jimmer/spring/cfg/SqlClientConfig.class]: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: `jdk.proxy2.$Proxy138` does not specify the type argument of `org.babyfish.jimmer.sql.filter.Filter`
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'kotlinSqlClient' threw exception with message: `jdk.proxy2.$Proxy138` does not specify the type argument of `org.babyfish.jimmer.sql.filter.Filter`
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: `jdk.proxy2.$Proxy138` does not specify the type argument of `org.babyfish.jimmer.sql.filter.Filter`
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.getImmutableType(FilterManager.java:366)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.filterMap(FilterManager.java:484)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager.<init>(FilterManager.java:63)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.createFilterManager(JSqlClientImpl.java:1324)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.build(JSqlClientImpl.java:1211)
	at org.babyfish.jimmer.sql.kt.cfg.KSqlClientDsl.buildKSqlClient$jimmer_sql_kotlin(KSqlClientDsl.kt:381)
	at org.babyfish.jimmer.sql.kt.KSqlClientKt.newKSqlClient(KSqlClient.kt:167)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig.kotlinSqlClient(SqlClientConfig.java:171)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.CGLIB$kotlinSqlClient$1(<generated>)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$SpringCGLIB$$0.kotlinSqlClient(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 34 common frames omitted
```

**Comment by babyfish-ct** [comment]
Try `0.8.19`

**Comment by JackyLeeCS** [comment]
可以了
