### ISSUE TITLE
@Serialize 对List的直接支持不完善

### ISSUE THREAD

**Issue by g770728y** [babyfish-ct/jimmer#279]
model
```
    @Serialized
    val desks: List<String>
```

读取无问题
但保存时报错：

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.List` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 18, column: 3]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
	at org.babyfish.jimmer.jackson.PropDeserializeUtils.readValue(PropDeserializeUtils.java:91)
	at org.babyfish.jimmer.jackson.PropDeserializeUtils.readTreeAsValue(PropDeserializeUtils.java:78)
	at org.babyfish.jimmer.jackson.PropDeserializeUtils.readTreeAsValue(PropDeserializeUtils.java:36)
	at org.babyfish.jimmer.jackson.ImmutableDeserializer.lambda$deserialize$0(ImmutableDeserializer.java:56)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:158)
	... 62 more
```

**Comment by aboutZZ** [comment]
说反了吧？应该是读取报错。
解决办法：
- 序列化时存储类名
- 使用具体实现类，例如：`ArrayList`

**Comment by g770728y** [comment]
1. 保存时报错，没有说反^_^
2. 序列化时存储类名， 这是指？ 
3. model里List改用ArrayList已经试过了，会报错 

@aboutZZ

**Comment by babyfish-ct** [comment]
Try `0.8.32`

**Comment by babyfish-ct** [comment]
Try `0.8.32`
