### ISSUE TITLE
[Feature Request]数据库表名用了数据库关键字时，希望可以在数据库校验时允许在实体的表名中加上``

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#328]
<img width="330" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/30ee15b0-86c6-4c16-8d4a-ed8d031bd03e">

表名用了数据库关键字，需要在实体中表名中加上``，但目前加上后数据库校验会通不过，关掉校验后是可以正常执行查询的。

校验错误日志：
```kotlin
- com.huashang.dao.jimmer.modules.common.entity.Order: There is no table "`order`"

	at org.babyfish.jimmer.sql.runtime.DatabaseValidators.validate(DatabaseValidators.java:94)
	at org.babyfish.jimmer.sql.runtime.DatabaseValidators.validate(DatabaseValidators.java:60)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.lambda$validateDatabase$1(JSqlClientImpl.java:1425)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:22)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.validateDatabase(JSqlClientImpl.java:1423)
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.lambda$build$0(JSqlClientImpl.java:1361)
	at org.babyfish.jimmer.sql.JSqlClientImpl$SqlClientInitializer.initialize(JSqlClientImpl.java:1496)
	at org.babyfish.jimmer.sql.JSqlClientImpl$SqlClientInitializer.access$000(JSqlClientImpl.java:1463)
	at org.babyfish.jimmer.sql.JSqlClientImpl.initialize(JSqlClientImpl.java:602)
	at org.babyfish.jimmer.sql.di.AbstractJSqlClientWrapper.initialize(AbstractJSqlClientWrapper.java:424)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.initialize(KSqlClientImpl.kt:144)
	at org.babyfish.jimmer.spring.cfg.SqlClientInitializer.run(SqlClientInitializer.java:29)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 14 common frames omitted
```

**Comment by babyfish-ct** [comment]
以前用户提过这个问题。但没有任何ORM提供这个功能。

最重要的原因，此举在某些数据库下会导致列的绝对大小写问题，脱离数据库全局配置，如此危险的功能没有ORM敢于内置。
