### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot find draft type for

### ISSUE THREAD

**Issue by BlueWolfStorm** [babyfish-ct/jimmer#331]
Ummmmm, I guess it's silly, I'm new using SpringBoot and I wanted to try this Orm, but I'm going crazy trying to initialize it (probably because of my inexperience) so these are my classes:

Gender.Kt
```
package com.btw.testappintellij.entities

import org.babyfish.jimmer.Immutable
import org.babyfish.jimmer.sql.*

@Entity
@Immutable
interface Gender{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id:Long
    val name:String
}
```

Main
```
@SpringBootApplication
class TestAppIntellijApplication

fun main(args: Array<String>) {
	val ctx = runApplication<TestAppIntellijApplication>(*args)
	val sqlClient = ctx.getBean(KSqlClient::class.java)

	val gender = sqlClient.createQuery(Gender::class){
		select(table)
	}.execute()

	println(gender)
}
```

build.gradle.kts
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "3.1.5"
	id("io.spring.dependency-management") version "1.1.3"
	kotlin("jvm") version "1.8.22"
	kotlin("plugin.spring") version "1.8.22"
}

group = "com.btw"
version = "0.0.1-SNAPSHOT"

java {
	sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
}

val jimmerVersion = "0.8.42"

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	runtimeOnly("mysql:mysql-connector-java:8.0.30")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.babyfish.jimmer:jimmer-spring-boot-starter:${jimmerVersion}")
	implementation("org.babyfish.jimmer:jimmer-sql-kotlin:${jimmerVersion}")
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs += "-Xjsr305=strict"
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.bootBuildImage {
	builder.set("paketobuildpacks/builder-jammy-base:latest")
}

```

application.properties, note: for obvious reasons I hide the ip, port and database. ;)
```
spring.datasource.url=jdbc:mysql://<secret>:<port>/<database>?useSSL=false
spring.datasource.username=<user>
spring.datasource.password=<password>

jimmer.language = kotlin
jimmer.dialect = org.babyfish.jimmer.sql.dialect.MySqlDialect
jimmer.show-sql = true
jimmer.pretty-sql = true
jimmer.database-validation-mode = ERROR
```

this is the error it gives me:

```
Caused by: java.lang.IllegalArgumentException: Cannot find draft type for "com.btw.testappintellij.entities.Gender"
	at org.babyfish.jimmer.meta.impl.Metadata.create(Metadata.java:70)
	at org.babyfish.jimmer.impl.util.StaticCache.get(StaticCache.java:58)
	at org.babyfish.jimmer.meta.impl.Metadata.get(Metadata.java:29)
	at org.babyfish.jimmer.meta.ImmutableType.get(ImmutableType.java:21)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.createQuery(KSqlClientImpl.kt:45)
	at com.btw.testappintellij.TestAppIntellijApplicationKt.main(TestAppIntellijApplication.kt:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 2 more

```
thanks in advance <3
I have read the documentation several times, but I will surely be blind enough to find the solution.

**Comment by babyfish-ct** [comment]
Jimmer requires code generation: https://babyfish-ct.github.io/jimmer/docs/overview/get-started/generate-code

The fastest learning way: https://babyfish-ct.github.io/jimmer/docs/overview/standard-demo

> Jimmer is not only a revolutionary ORM, but also a comprehensive solution based on it. So it is a feature-rich framework with a large scope. No matter how the documentation is designed, it is impossible to clearly explain everything with little text like frameworks with very small scope.
> 
> For relatively large-scale frameworks, examples can significantly improve learning efficiency, which is as important as documentation.
