### ISSUE TITLE
Springboot start failed when set `jimmer.client.ts.path`

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#354]
`Springboot`工程，当在配置文件中设置`jimmer.client.ts.path=/debug/ts.zip`后，项目启动失败：
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
14:35:14.096 ERROR : Application run failed
java.lang.NullPointerException: Cannot invoke "kotlin.reflect.KType.getAnnotations()" because "type" is null
	at io.elva.AppServerApplicationKt.main(AppServerApplication.kt:44) [36 skipped]
	... 29 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metadataFactoryBean': FactoryBean threw exception on object creation
	at io.elva.AppServerApplicationKt.main(AppServerApplication.kt:44) [29 skipped]
	... 19 common frames omitted
Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'typeScriptController' defined in class path resource [org/babyfish/jimmer/spring/cfg/ServletControllerConfiguration.class]: Unsatisfied dependency expressed through method 'typeScriptController' parameter 0: Error creating bean with name 'metadataFactoryBean': FactoryBean threw exception on object creation
	at io.elva.AppServerApplicationKt.main(AppServerApplication.kt:44) [19 skipped]
```

看起来是`TypeScriptController` 构造函数中 `Metadata` bean 创建失败，NPE

**Comment by babyfish-ct** [comment]
是的，这个部分在重写中，客户端的注释不应该采用swagger类似侵入式注解，而因该直接抽取Java/Kotlin的文档注释。

所以，目前正在从runtime方案改为compile-time方案，Fix没有意义，抱歉，需要等待。

**Comment by babyfish-ct** [comment]
Try `0.8.64`
