### ISSUE TITLE
[KSP] Incompatibility with micronaut ksp processor

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#378]
1. create kotlin project with gradle-kotlin build from https://micronaut.io/launch/
2. apply `jimmer ksp` and create demo model with `@Entity` annotation
3. `./gradlew build  --debug` fails with exception

```
2024-01-12T21:51:52.780+0300 [DEBUG] [org.gradle.api.Task] v: [ksp] round 1 of processing
2024-01-12T21:51:52.780+0300 [INFO] [org.gradle.api.Task] i: [ksp] loaded provider(s): [io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessorProvider, io.micronaut.kotlin.processing.beans.BeanDefinitionProcessorProvider, org.babyfish.jimmer.ksp.JimmerProcessorProvider]
2024-01-12T21:51:52.780+0300 [DEBUG] [org.gradle.api.Task] v: [ksp] round 2 of processing
2024-01-12T21:51:52.780+0300 [ERROR] [org.gradle.api.Task] e: [ksp] org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration OBJECT_DECLARATION
        at org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:17)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:91)
        at org.jetbrains.kotlin.resolve.lazy.ResolveSession.resolveToDescriptor(ResolveSession.java:368)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveDeclaration(ResolverImpl.kt:498)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.resolveClassDeclaration(ResolverImpl.kt:545)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignatureInternal$compiler_plugin(ResolverImpl.kt:340)
        at com.google.devtools.ksp.processing.impl.ResolverImpl.mapToJvmSignature(ResolverImpl.kt:337)
        at io.micronaut.kotlin.processing.ExtensionsKt.getBinaryName(extensions.kt:50)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinElement.resolveDeclaringType(AbstractKotlinElement.kt:195)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$resolvedDeclaringType$2.invoke(AbstractKotlinPropertyElement.kt:66)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$resolvedDeclaringType$2.invoke(AbstractKotlinPropertyElement.kt:65)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getResolvedDeclaringType(AbstractKotlinPropertyElement.kt:65)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getDeclaringType(AbstractKotlinPropertyElement.kt:99)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$resolvedGenericType$2.invoke(KotlinPropertyElement.kt:52)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$resolvedGenericType$2.invoke(KotlinPropertyElement.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement.getResolvedGenericType(KotlinPropertyElement.kt:51)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getGenericType(AbstractKotlinPropertyElement.kt:85)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyGetterMethodElement.<init>(KotlinPropertyGetterMethodElement.kt:58)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyGetterMethodElement.<init>(KotlinPropertyGetterMethodElement.kt:47)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2$1.invoke(KotlinPropertyElement.kt:81)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2$1.invoke(KotlinPropertyElement.kt:80)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke$lambda$0(KotlinPropertyElement.kt:80)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke(KotlinPropertyElement.kt:80)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke(KotlinPropertyElement.kt:78)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement.getGetter(KotlinPropertyElement.kt:78)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$internalAnnotationMetadata$2.invoke(AbstractKotlinPropertyElement.kt:57)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$internalAnnotationMetadata$2.invoke(AbstractKotlinPropertyElement.kt:54)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getInternalAnnotationMetadata(AbstractKotlinPropertyElement.kt:54)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getAnnotationMetadata(AbstractKotlinPropertyElement.kt:87)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getAnnotationMetadata(AbstractKotlinPropertyElement.kt:32)
        at io.micronaut.core.annotation.AnnotationMetadataDelegate.hasAnnotation(AnnotationMetadataDelegate.java:514)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2$3.invoke(KotlinClassElement.kt:136)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2$3.invoke(KotlinClassElement.kt:136)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2.invoke(KotlinClassElement.kt:137)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2.invoke(KotlinClassElement.kt:125)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getDeclaredNativeProperties(KotlinClassElement.kt:125)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getDeclaredSyntheticBeanProperties(KotlinClassElement.kt:295)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.access$getDeclaredSyntheticBeanProperties(KotlinClassElement.kt:38)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$nativeProperties$2.invoke(KotlinClassElement.kt:119)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$nativeProperties$2.invoke(KotlinClassElement.kt:113)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getNativeProperties(KotlinClassElement.kt:113)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getSyntheticBeanProperties(KotlinClassElement.kt:293)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitMembers(TypeElementSymbolProcessor.kt:281)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitClassDeclaration(TypeElementSymbolProcessor.kt:262)
        at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:135)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor.process(TypeElementSymbolProcessor.kt:124)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:306)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:304)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:410)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:304)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:181)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)


```

**Comment by a8t3r** [comment]
@babyfish-ct After some research I noticed [micronaut](https://github.com/micronaut-projects/micronaut-core/blob/8c84c94f726aeb577283d9aad255a8074b1419ec/inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt#L148C17-L148C17) ignores all type declarations with `@Generated` annotation.
I think the simplest workaround for that issue is to add additional annotation based on user config/env.

**Comment by babyfish-ct** [comment]
Thanks for your research and suggestion, this week I have time to look at this issue.

**Comment by babyfish-ct** [comment]
> @babyfish-ct After some research I noticed [micronaut](https://github.com/micronaut-projects/micronaut-core/blob/8c84c94f726aeb577283d9aad255a8074b1419ec/inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/TypeElementSymbolProcessor.kt#L148C17-L148C17) ignores all type declarations with `@Generated` annotation. I think the simplest workaround for that issue is to add additional annotation based on user config/env.

My framework uses `@org.babyfish.jimmer.internal.GeneratedBy` which is not `@Generated`

**Comment by babyfish-ct** [comment]
@a8t3r Sorry, I don't know the reason, so I forward it to `https://github.com/micronaut-projects/micronaut-core/discussions/10388` for help.

**Comment by babyfish-ct** [comment]
micronaut let's wait for its 4.3 release, and if there are still problems with the micronaut 4.3 release, please reopen it.

BTW, the new section `quickview` of documentation is very helpful: https://babyfish-ct.github.io/jimmer-doc/docs/quick-view/
