### ISSUE TITLE
Repository可以提供通过Predicate进行查询的方法吗

### ISSUE THREAD

**Issue by Guigumua** [babyfish-ct/jimmer#40]
版本: 0.7.0

JRepository或KJRepository中没有提供`findAll(Predicate predicate)`和`findOne(Predicate predicate)`这样的方法
类似QueryDsl中的`QuerydslPredicateExecutor`:
```java
public interface QuerydslPredicateExecutor<T> {
        Optional<T> findOne(Predicate predicate);

	Iterable<T> findAll(Predicate predicate);
}
```
是否可以考虑实现这样的方法呢?

我尝试实现这样的方法时, 碰到了一个问题

SqlClient没有`createQuery(Class<?> entityClass)`这样能够基于实体类型创建查询的方法, 只有通过`Table<E>`创建查询的方法, 因此必须通过repository提供`Table`对象才可能实现.
例如:
```java
public interface BaseJimmerRepository<E, ID> extends JRepository<E, ID> {

  <T extends TableProxy<E>> T table();

  default List<E> findAll(Predicate predicate) {
    return sql().createQuery(table()).where(predicate).select(table()).execute();
  }
}
```
实体的Repository:
```java
public interface DeviceJimmerRepository extends BaseJimmerRepository<Device,Long> {
   @Override default DeviceTable table() {
    return DeviceTable.$;
  }
}
```

Repository中能内置实现这种方法吗, 亦或者提供方便检索实体对应的`Table`的方法呢?

------------------------------------编辑

我找到了JRepositoryImpl中的一个方法`org.babyfish.jimmer.spring.repository.support.JRepositoryImpl#createQuery`
```java
    private ConfigurableRootQuery<?, E> createQuery(Fetcher<E> fetcher, TypedProp.Scalar<?, ?>[] sortedProps) {
        MutableRootQueryImpl<Table<E>> query =
                new MutableRootQueryImpl<>(sqlClient, immutableType, ExecutionPurpose.QUERY, false);
        Table<E> table = query.getTable();
        for (TypedProp.Scalar<?, ?> sortedProp : sortedProps) {
            if (!sortedProp.unwrap().getDeclaringType().isAssignableFrom(immutableType)) {
                throw new IllegalArgumentException(
                        "The sorted field \"" +
                                sortedProp +
                                "\" does not belong to the type \"" +
                                immutableType +
                                "\" or its super types"
                );
            }
            PropExpression<?> expr = table.get(sortedProp.unwrap().getName());
            Order astOrder;
            if (sortedProp.isDesc()) {
                astOrder = expr.desc();
            } else {
                astOrder = expr.asc();
            }
            if (sortedProp.isNullsFirst()) {
                astOrder = astOrder.nullsFirst();
            }
            if (sortedProp.isNullsLast()) {
                astOrder = astOrder.nullsLast();
            }
            query.orderBy(astOrder);
        }
        query.freeze();
        return query.select(fetcher != null ? table.fetch(fetcher) : table);
    }
```

也许我知道该怎么自己实现了

----------------------------编辑

出问题了
jdk版本: 17
jimmer版本: 0.7.0
异常栈:
```shell
java.lang.IllegalArgumentException: Cannot resolve the root table xxx.xxx.xxx.Device
	at org.babyfish.jimmer.sql.ast.impl.AstContext.resolveRootTable(AstContext.java:85) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.table.spi.AbstractTypedTable.__resolve(AbstractTypedTable.java:334) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.table.TableProxies.resolve(TableProxies.java:142) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.PropExpressionImpl.accept(PropExpressionImpl.java:109) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.ComparisonPredicate.accept(ComparisonPredicate.java:26) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.AbstractMutableQueryImpl.accept(AbstractMutableQueryImpl.java:191) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.AbstractConfigurableTypedQueryImpl.accept(AbstractConfigurableTypedQueryImpl.java:53) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.accept(ConfigurableRootQueryImpl.java:21) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.preExecute(ConfigurableRootQueryImpl.java:201) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:155) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.spring.repository.SpringConnectionManager.execute(SpringConnectionManager.java:22) ~[jimmer-spring-boot-starter-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:135) ~[jimmer-sql-0.7.0.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:21) ~[jimmer-sql-0.7.0.jar:na]
	at xxx.xxx.xxx.xxx..xxx.BaseJimmerRepository.findAll(BaseJimmerRepository.java:69) ~[classes/:na]
```

其中`BaseJimmerRepository`中的代码如下:
```java
@NoRepositoryBean
public interface BaseJimmerRepository<E>
    extends JRepository<E, Long> {

  private ConfigurableRootQuery<?, E> createQuery(
      Predicate predicate, Fetcher<E> fetcher, TypedProp.Scalar<?, ?>[] sortedProps) {
    var immutableType = type();
    MutableRootQueryImpl<Table<E>> query =
        new MutableRootQueryImpl<>(sql(), immutableType, ExecutionPurpose.QUERY, false);
    Table<E> table = query.getTable();
    for (TypedProp.Scalar<?, ?> sortedProp : sortedProps) {
      if (!sortedProp.unwrap().getDeclaringType().isAssignableFrom(immutableType)) {
        throw new IllegalArgumentException(
            "The sorted field \""
                + sortedProp
                + "\" does not belong to the type \""
                + immutableType
                + "\" or its super types");
      }
      PropExpression<?> expr = table.get(sortedProp.unwrap().getName());
      Order astOrder;
      if (sortedProp.isDesc()) {
        astOrder = expr.desc();
      } else {
        astOrder = expr.asc();
      }
      if (sortedProp.isNullsFirst()) {
        astOrder = astOrder.nullsFirst();
      }
      if (sortedProp.isNullsLast()) {
        astOrder = astOrder.nullsLast();
      }
      query.orderBy(astOrder);
    }
    var tableMutableRootQuery = query.where(predicate);
    query.freeze(); 
    return tableMutableRootQuery.select(fetcher != null ? table.fetch(fetcher) : table);
  }

  default List<E> findAll(Predicate predicate) {
    return createQuery(predicate).execute(); // 调用execute报错
  }
```
controller调用的代码
```java
  @GetMapping("test")
  public List<xxx.xxx.xxx.xxx.Device> test() {
    return deviceJimmerRepository.findAll(DeviceTable.$.mac().eq("0011AABBCC00"));
  }
```

看起来是`MutableRootQueryImpl`的`getTable`返回的`Table`不能用来组成条件.

所以还是回到最开始的问题: 是否考虑由Repository提供通过Predicate的查询, 或可以通过实体类检索Table对象的方法, 如果不考虑的话, 我就只能采用实体的Repository提供table的方式了.

**Comment by babyfish-ct** [comment]
# 你遇到了什么问题？

“Cannot resolved...”的意思：XXXTable.$只是一个无状态符号，底层需要解析成优状态的真实Table，比如

```
BookTable book = BookTable.$;

List<Book> newestBooks = sqlClient
    .createQuery(book)
    .where(
        Expression.tuple(
            book.name(),
            book.edition()
        ).in(sqlClient
            .createSubQuery(book)
            .groupBy(book.name())
            .select(
                book.name(),
                book.edition().max()
            )
        )
    )
    .select(book)
    .execute();
```

这里父子查询的都基于`book`这个无状态的符号，但很明显，底层是两个不同的有状态的表。从无状态的符号到有状态的表的解析过程，称之为resolve。

为什么底层表是有状态的？请参考冲突连接自动合并：https://babyfish-ct.github.io/jimmer/zh/docs/jimmer-sql/basic/table-join#%E5%86%B2%E7%AA%81%E5%90%88%E5%B9%B6%E8%A7%84%E5%88%99，Jimmer并不打算提供QueryDsl或JOOQ那种机械的SQL字面翻译DSL，而是要改变SQL的玩法，创建超越原生SQL，"Not only dynamic predicates, but also dynamic table joins"。这是Jimmer一个非常强大的能力，现有用户非常喜欢，此功能也是最初Jimmer项目创建的根本原因。

要实现这个强大的功能，就必须完成从无状态的符号到有状态的表的reolve过程，这就表示查询（或父查询）from中的符号，和SQL表达式中使用的符号，必须是同一个对象。form建立无状态符号和有状态地层表的映射，其他表达式把任何地方所引用的符号翻译成有状态表。

你上面的做法，from创建的无符号和SQL表达式中使用的符号不同，导致无法解析。

# 如果解决遇到的问题？

Jimmer中有两种查询方法：

1. 基于Lambda的查询，不会用符号XXXTable.$，而是MutableQuery内部创建符号，该符号作为lambda的参数暴露给lambda，lambda中的SQL DSL用它，这种API主要是kotlin查询使用(kotlin也不使用XXXTable.$, kt下也根本不会生成XXXTable.$)

2. 基于Fluent的查询，因为Java的Lambda远没有kotlin那么给力，所以Java下使用另外一种非Lambda的查询，这种情况下，不用Lambda, 不自动创建符号，而是from现成的符号（XXXTable.$)。

所以

```
new MutableRootQueryImpl<>(
         this,
         this.table(), //第二个参数变了
         ExecutionPurpose.QUERY,
         false
 )
```

这里，第二个参数不再是immutableType, 那是Lambda风格查询，而是改了你写的抽象的`table()`函数，使用现成的table，这就是Java兼容的Fluent查询。换写成这样后。你的问题就可以解决。

# 为什么不支持QueryDsl风格的Predicate?

对于动态查询而言，简单的可以靠QBE(findByExample)甚至是约定的抽象方法（约定的抽象方法也是动态查询）,复杂的可以用default方法各种whereIf， 请参见https://github.com/babyfish-ct/jimmer/blob/main/example/java/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/example/dal/BookRepository.java

所以，无论是简单的动态查询，还是极其复杂复杂的，Jimmer都可以把参数传递给数据层并完美实现。QueryDSL那种吧predicate暴露出去并允许模糊话数据层和业务层的边界的做法，并不认可。

**Comment by Guigumua** [comment]
> 

好的我明白了

**Comment by babyfish-ct** [comment]
如果的确要这样做，两个办法选一个

1. 业务层给予XXXTable.$创建各种Predicate以及他们的and, or, not(and, or本身只是变参，而且每个都可null，动态and和or很简单)，底层repository内部from也基于XXXTable.$，上下两层table一致即可。

2. 参数时一个lamba，接受table，返回Predicate(or null)

上个回复其实已经包含这个答案了。table敏感是“自动合并冲突动态join“这个强大能力的必然副作用，不可能提供机械SQL翻译方案中的table不敏感predicate.
