### ISSUE TITLE
Repository层自定义方法入参异常：Too many parameters

### ISSUE THREAD

**Issue by 2200404400** [babyfish-ct/jimmer#400]
版本
=
SpringBoot：3.0.2
Jimmer：0.8.83
Kotlin：1.6.21
Jdk：17

问题描述
=
在Repository类里面定义一个方法，方法入参对象有继承关系则会发生该问题

代码
=
**Repository类**
```kotlin
interface BaseRepository<
    ID : Any,
    FindVO : BaseTreeFindVO,
    Model : BaseModel,
    > : KRepository<Model, ID> {

    fun count(vo: FindVO): Long {
        return 0
    }
}
```

**实体类**
```kotlin
open class BaseTreeFindVO : BaseFindVO()
```

**被继承的类**
```kotlin
open class BaseFindVO {
    open var id: StrField? = null
    open var updateTime: CmpField<LocalDateTime>? = null
    open var createTime: CmpField<LocalDateTime>? = null
}
```

异常信息
=
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'regionRepository' defined in org.aroma.sweetness.consumer.project.repository.RegionRepository defined in @EnableJimmerRepositories declared on JimmerRepositoriesRegistrar.EnableJimmerRepositoriesConfiguration: Illegal abstract spring-data method "public abstract long org.aroma.sweetness.consumer.common.repository.BaseRepository.count(org.aroma.sweetness.api.common.vo.BaseTreeFindVO)": Too many parameters
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:490) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:467) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:618) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:242) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:133) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:300) ~[spring-context-6.0.4.jar:6.0.4]
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: Illegal abstract spring-data method "public abstract long org.aroma.sweetness.consumer.common.repository.BaseRepository.count(org.aroma.sweetness.api.common.vo.BaseTreeFindVO)": Too many parameters
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:88) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:80) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethod.of(QueryMethod.java:46) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.bytecode.MethodCodeWriter.write(MethodCodeWriter.java:38) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.bytecode.KotlinMethodCodeWriter.write(KotlinMethodCodeWriter.java:44) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.bytecode.ClassCodeWriter.write(ClassCodeWriter.java:113) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.support.JimmerRepositoryFactory.getTargetRepository(JimmerRepositoryFactory.java:111) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:317) ~[spring-data-commons-3.0.1.jar:3.0.1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279) ~[spring-data-commons-3.0.1.jar:3.0.1]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245) ~[spring-data-commons-3.0.1.jar:3.0.1]
	at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[spring-data-commons-3.0.1.jar:3.0.1]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285) ~[spring-data-commons-3.0.1.jar:3.0.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-beans-6.0.4.jar:6.0.4]
	... 48 common frames omitted
Caused by: java.lang.IllegalArgumentException: Too many parameters
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse0(QueryMethodParser.java:106) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:85) ~[jimmer-spring-boot-starter-0.8.83.jar:na]
	... 61 common frames omitted
```

**Comment by babyfish-ct** [comment]
现阶段，抽象Repository不支持对象类型复合参数，暂不处理。且方法名和参数形式有严格约定（和Spring Data约定类似）

Spring-Data约定抽象方法在Jimmer下用途很小，相对鸡肋，可以不用

**Comment by babyfish-ct** [comment]
按目前规划，不支持对象类型复合参数只是一方面。另外一方面，用法是错误的。

正确的用法和Spring Data类似，请参考https://docs.spring.io/spring-data/jpa/reference/repositories/query-keywords-reference.html。这个链接比较详细。

不难看出，按照此约定编程，参数越复杂，方法名会越长。Spring Data约定很鸡肋，用户们也不喜欢（可以通过资源篇加入用户群），现在几乎无人使用（当时支持部分这类约定式编程知识为了哄spring用户开心）
