### ISSUE TITLE
0.8.94新版本的逻辑删除逻辑问题，当配置了joinTable的逻辑处理过滤器报错

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#440]
# 版本

- jimmer：0.8.94
- springboot：2.7.18
- kotlin：1.9.22
- jdk：11
- 构建：maven3

# 问题描述

官方例子中：基于`book`、 `author` 、 `book_author_mapping` 都添加逻辑删除字段   `deleted` （数字 0表示未删除  1表示已删除）

## 期望

当根据 book的id删除书籍时候  逻辑删除`book`  同时逻辑删除中间表  `book_author_mapping` 的关联 即能够有如下sql效果：

```sql
update book set deleted = 1 where id = xxxxx

update book_author_mapping set deleted = 1 where book_id = xxxxx

```

## 实践问题

配置JoinTable：

核心配置： ` logicalDeletedFilter = LogicalDeletedFilter(columnName = "deleted", type = Int::class,  value = "1")`

```kotlin
    @ManyToMany // ❹
    @JoinTable(
        name = "BOOK_AUTHOR_MAPPING",
        joinColumnName = "BOOK_ID",
        inverseJoinColumnName = "AUTHOR_ID",
        logicalDeletedFilter = LogicalDeletedFilter(columnName = "deleted", type = Int::class,  value = "1")
    )
    val authors: List<Author>
```

项目启动时报错：
```bash

Caused by: org.babyfish.jimmer.meta.ModelException: Illegal property "org.babyfish.jimmer.sql.example.kt.model.Book.authors", it is decorated by `@org.babyfish.jimmer.sql.LogicalDeleted` and its type is the time type "long", but the `value` is "1" which is neither "null" or "now"
	at org.babyfish.jimmer.meta.LogicalDeletedInfo.parseValue(LogicalDeletedInfo.java:569) ~[jimmer-core-0.8.9888.jar:na]
	at org.babyfish.jimmer.meta.LogicalDeletedInfo.of(LogicalDeletedInfo.java:339) ~[jimmer-core-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.association.meta.AssociationType.<init>(AssociationType.java:69) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.impl.util.PropCache.get(PropCache.java:79) ~[jimmer-core-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.association.meta.AssociationType.of(AssociationType.java:39) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.createRawTypeMap(EntityManager.java:712) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.createTypeMap(EntityManager.java:624) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.meta.impl.MetaCache.get(MetaCache.java:58) ~[jimmer-core-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.getTypeMap(EntityManager.java:619) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager.validate(EntityManager.java:397) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.build(JSqlClientImpl.java:1350) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.di.JLazyInitializationSqlClient.sqlClient(JLazyInitializationSqlClient.java:61) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.di.JLazyInitializationSqlClient.getEntities(JLazyInitializationSqlClient.java:129) ~[jimmer-sql-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.<init>(KSqlClientImpl.kt:77) ~[jimmer-sql-kotlin-0.8.9888.jar:na]
	at org.babyfish.jimmer.sql.kt.KSqlClientKt.toKSqlClient(KSqlClient.kt:243) ~[jimmer-sql-kotlin-0.8.9888.jar:na]
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig.kotlinSqlClient(SqlClientConfig.java:33) ~[jimmer-spring-boot-starter-0.8.9888.jar:na]
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$EnhancerBySpringCGLIB$$6f902ddd.CGLIB$kotlinSqlClient$1(<generated>) ~[jimmer-spring-boot-starter-0.8.9888.jar:na]
	at org.babyfish.jimmer.spring.cfg.SqlClientConfig$$EnhancerBySpringCGLIB$$6f902ddd$$FastClassBySpringCGLIB$$3e363536.invoke(<generated>) ~[jimmer-spring-boot-starter-0.8.9888.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.20.jar:5.3.20]
```

**Comment by qinkangdeid** [comment]
debug代码跟踪能够查看到：当扫描扫实体类当中的 **关联属性**的时候装载LogicalDeletedInfo在判断type的类型的时候就会出错    源码在`LogicalDeletedInfo`代码第219行判断了逻辑删除字段的类型 


尝试修改源码验证:

###  方式一：
在 org.babyfish.jimmer.meta.LogicalDeletedInfo#parseValue方法中  `        Class<?> type = prop.getElementClass();
` 语句前 添加：
![c64c401b88f1132000073f196b89fafc](https://github.com/babyfish-ct/jimmer/assets/17582522/c0996418-255e-424c-8ca2-75f6a8c9fbec)
本意是想跳过 关联属性 的类型判断

运行 启动成功 
执行删除api的时候 删除中间表的时候经过JoinTableFilter(代码第29行)获取不到LogicalDeletedInfo的值（因为是null）报空指针错误
![93452799676acd6a9a52076f5b65fbdc](https://github.com/babyfish-ct/jimmer/assets/17582522/48df228c-1955-44d6-a849-825c3f6ebcb7)

### 方式二

修改parseValue方法 增加一个参数returnType
 方法内部不使用prop参数判断类型  使用上面逻辑的returnType来判断类型
![20fb3b5ae72017acf5ff543264ec73bd](https://github.com/babyfish-ct/jimmer/assets/17582522/f29c2270-fb9d-403a-9e3f-f6661e72e847)


运行测试：
启动正常：
能解析出正确的字段和逻辑删除值    
但是运行测试的时候必须要配置一个 initializedValue 的值  不配置的话 会在代码379行处报错：
 
![1cb21347bcbd099115e462b76e019513](https://github.com/babyfish-ct/jimmer/assets/17582522/e6bb0be4-6eb5-4912-9506-0b753439d19d)


根据提示修改 添加 initializedValue
![35d95731510b4eebd08c845d90d17651](https://github.com/babyfish-ct/jimmer/assets/17582522/5998829f-0cb0-4ab3-aa90-e52e7f3c5f50)

最终运行：
<img width="1520" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/882a0ea6-d2c0-4071-9204-3ad93dded87d">


对jimmer源码不熟悉 这是我的debug与自认为的修改过程  给大佬一个参考

**Comment by babyfish-ct** [comment]
Try `0.8.99`
