### ISSUE TITLE
mysql中表名为关键字，添加`转义符时，数据库校验失败

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#450]
`2024-03-08 17:46:59.079  WARN 85309 --- [           main] o.b.j.sql.JSqlClientImpl$BuilderImpl     : Failed to validate database: 
- com.example.demo.entity.Order: There is no table "`order`"

org.babyfish.jimmer.sql.runtime.DatabaseValidationException: Failed to validate database: 
- com.example.demo.entity.Order: There is no table "`order`"

	at org.babyfish.jimmer.sql.runtime.DatabaseValidators.validate(DatabaseValidators.java:94) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.runtime.DatabaseValidators.validate(DatabaseValidators.java:60) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.lambda$validateDatabase$1(JSqlClientImpl.java:1508) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28) ~[jimmer-spring-boot-starter-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.validateDatabase(JSqlClientImpl.java:1506) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.lambda$build$0(JSqlClientImpl.java:1444) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$SqlClientInitializer.initialize(JSqlClientImpl.java:1579) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$SqlClientInitializer.access$000(JSqlClientImpl.java:1546) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl.initialize(JSqlClientImpl.java:667) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.sql.di.AbstractJSqlClientDelegate.initialize(AbstractJSqlClientDelegate.java:341) ~[jimmer-sql-0.8.104.jar:na]
	at org.babyfish.jimmer.spring.cfg.SqlClientInitializer.run(SqlClientInitializer.java:26) ~[jimmer-spring-boot-starter-0.8.104.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:756) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:746) ~[spring-boot-2.7.18.jar:2.7.18]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.18.jar:2.7.18]
	at com.example.demo.Demo1Application.main(Demo1Application.java:10) ~[classes/:na]`

**Comment by Atomzzm** [comment]
通过实体接口类增加```@DatabaseValidationIgnore```注解解决了。
```@DatabaseValidationIgnore```是否可以支持更细粒度的校验选项。
