### ISSUE TITLE
[Bug] 使用 `exists(subQuery)` 进行条件过滤子查询时，`select(table)` 导致报错

### ISSUE THREAD

**Issue by ArgonarioD** [babyfish-ct/jimmer#453]
## 导致报错的代码
```kotlin
// CityResource.kt
sqlClient.createQuery(Place::class) {
    where += and(
        table.city.id eq cityId,
        or(
            table.isUpdated eq true,
            exists(subQuery(Announcement::class) {  // 本行为第63行
                where += table.place eq parentTable
                select(table)  // 本行为第65行
            })
        )
    )
    orderBy(table.cardCount.asc(), table.updateTime.desc())
    select(table.fetchBy {
        allScalarFields()
        announcements()
    })
}.execute()
```
## 错误日志
```
java.lang.ClassCastException: class org.babyfish.jimmer.sql.kt.ast.table.impl.KNonNullTableExImpl cannot be cast to class org.babyfish.jimmer.sql.ast.impl.ExpressionImplementor (org.babyfish.jimmer.sql.kt.ast.table.impl.KNonNullTableExImpl and org.babyfish.jimmer.sql.ast.impl.ExpressionImplementor are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @71238fc2)
    at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableSubQueryImpl.<init>(ConfigurableSubQueryImpl.java:36)
    at org.babyfish.jimmer.sql.ast.impl.query.MutableSubQueryImpl.select(MutableSubQueryImpl.java:154)
    at org.babyfish.jimmer.sql.kt.ast.query.impl.KMutableSubQueryImpl.select(KMutableSubQueryImpl.kt:81)
    at io.github.argonariod.bot.maij.resource.CityResource$getCityCardStatusSorted$1$1.invoke(CityResource.kt:65)
    at io.github.argonariod.bot.maij.resource.CityResource$getCityCardStatusSorted$1$1.invoke(CityResource.kt:63)
    at org.babyfish.jimmer.sql.kt.impl.KSubQueriesImpl.forEntity(KSubQueriesImpl.kt:29)
    at org.babyfish.jimmer.sql.kt.ast.query.AbstractKFilterable$DefaultImpls.subQuery(AbstractKFilterable.kt:24)
    at org.babyfish.jimmer.sql.kt.ast.query.KFilterable$DefaultImpls.subQuery(KFilterable.kt:5)
    at org.babyfish.jimmer.sql.kt.ast.query.KSortable$DefaultImpls.subQuery(KSortable.kt:5)
    at org.babyfish.jimmer.sql.kt.ast.query.KMutableQuery$DefaultImpls.subQuery(KMutableQuery.kt:6)
    at org.babyfish.jimmer.sql.kt.ast.query.KMutableRootQuery$DefaultImpls.subQuery(KMutableRootQuery.kt:5)
    at org.babyfish.jimmer.sql.kt.ast.query.impl.KMutableRootQueryImpl.subQuery(KMutableRootQueryImpl.kt:28)
    at io.github.argonariod.bot.maij.resource.CityResource$getCityCardStatusSorted$1.invoke(CityResource.kt:63)
    at io.github.argonariod.bot.maij.resource.CityResource$getCityCardStatusSorted$1.invoke(CityResource.kt:58)
    at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.createQuery(KSqlClientImpl.kt:52)
    at org.babyfish.jimmer.sql.kt.DatabaseDependent_ProducerMethod_sqlClient_Hhp707FXa-LECY3qQL6eMJGkXyo_ClientProxy.createQuery(Unknown Source)
    at io.github.argonariod.bot.maij.resource.CityResource.getCityCardStatusSorted(CityResource.kt:58)
    at io.github.argonariod.bot.maij.resource.CityResource_Subclass.getCityCardStatusSorted$$superforward(Unknown Source)
    at io.github.argonariod.bot.maij.resource.CityResource_Subclass$$function$$7.apply(Unknown Source)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
    at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
    at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
    at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
    at io.github.argonariod.bot.maij.resource.CityResource_Subclass.getCityCardStatusSorted(Unknown Source)
    at io.github.argonariod.bot.maij.resource.CityResource$quarkusrestinvoker$getCityCardStatusSorted_a9f9070756afbac4e8764a5867eeab3a8d0a3a86.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
    at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```
## 涉及到的模型部分定义
- `Place` 对 `Announcement` 为一对多关系
- `Announcement` 中有逻辑删除字段
## 其它
- 当将子查询中的 `select(table)` 改为 `select(table.id)` 后程序正常工作。
- 导致异常的代码参考了文档中的此段 [查询篇 > 子查询 > 使用exists运算符](https://babyfish-ct.gitee.io/jimmer-doc/docs/query/sub-query#%E4%BD%BF%E7%94%A8exists%E8%BF%90%E7%AE%97%E7%AC%A6) 中的示例代码。

**Comment by babyfish-ct** [comment]
Try `0.8.105`
