### ISSUE TITLE
[bug] Can't save entity with embeddable explicitly set to null

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#468]
```
@Entity
interface MyEntity {
    ...
    val nested: MyEmbeddable?
}

@Embeddable
interface MyEmbeddable {
    val myValue: String?
}

sql.insert(new(MyEntity::class).by {
    nested = null
})
```

Cannot invoke "org.babyfish.jimmer.meta.ImmutableProp.getElementClass()" because the return value of "org.babyfish.jimmer.meta.ImmutableType.getIdProp()" is null
java.lang.NullPointerException: Cannot invoke "org.babyfish.jimmer.meta.ImmutableProp.getElementClass()" because the return value of "org.babyfish.jimmer.meta.ImmutableType.getIdProp()" is null
	at org.babyfish.jimmer.sql.runtime.SqlBuilder.nullVariable(SqlBuilder.java:526)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.insert(Saver.java:555)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:409)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveImpl(Saver.java:122)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:103)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:158)
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42)
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:92)
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:99)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:67)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:61)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:12)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.save(KEntitiesImpl.kt:196)
	at org.babyfish.jimmer.sql.kt.KEntities$DefaultImpls.save$default(KEntities.kt:60)
	at org.babyfish.jimmer.sql.kt.KSqlClient$DefaultImpls.save(KSqlClient.kt:119)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImplementor$DefaultImpls.save(KSqlClientImplementor.kt:7)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.save(KSqlClientImpl.kt:34)
	at org.babyfish.jimmer.sql.kt.KSqlClient$DefaultImpls.insert(KSqlClient.kt:127)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImplementor$DefaultImpls.insert(KSqlClientImplementor.kt:7)
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.insert(KSqlClientImpl.kt:34)

**Comment by belovaf** [comment]
When I set manually all nested fields inside an embeddable all works fine:
```
sql.insert(new(MyEntity::class).by {
    nested().apply {
        myValue = null
    }
})
```

**Comment by babyfish-ct** [comment]
Try `0.8.112` please
