### ISSUE TITLE
Add support for object attributes with the Object type for the TS client

### ISSUE THREAD

**Issue by leeaee** [babyfish-ct/jimmer#503]
Source code like
```
private Map<String, Object> additionalInfo;
```
or
```
private List<Object> content;
```
When download the ts.zip, Jimmer will throw exception like
```
org.babyfish.jimmer.client.runtime.TypeResolvingException: Cannot resolve type via the chain: com.dabaobe.nexus.common.data.model.entities.system.Client@additionalInfo
	at org.babyfish.jimmer.client.runtime.impl.FetchedTypeImpl.initProperties(FetchedTypeImpl.java:110)
	at org.babyfish.jimmer.client.runtime.impl.FetchedTypeImpl.init(FetchedTypeImpl.java:54)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.fetchedType(TypeContext.java:175)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseNonNullType(TypeContext.java:114)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseType(TypeContext.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseNonNullType(TypeContext.java:128)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseType(TypeContext.java:88)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.operation(MetadataBuilder.java:258)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.service(MetadataBuilder.java:182)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.build(MetadataBuilder.java:119)
	at org.babyfish.jimmer.spring.client.Metadatas.create(Metadatas.java:49)
	at org.babyfish.jimmer.spring.client.TypeScriptController.download(TypeScriptController.java:26)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:925)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:830)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
```
Could Jimmer add support for object attributes with the `Object` type for the TS client?

**Comment by babyfish-ct** [comment]
Try `0.8.119`
