### ISSUE TITLE
多对多映射中简单计算属性依赖关联属性在从动方失效

### ISSUE THREAD

**Issue by Xspana** [babyfish-ct/jimmer#522]
多对多映射中简单计算属性依赖关联属性，在主动方是正常的，在从动方就会报异常

> 经测试，在一对多映射中也有这个问题

# # 问题描述

标签表（Tag）与文章表（Article）是多对多的关系

Article.java 主动方

```java
@Entity
public interface Article extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id();

    //其它属性已省略

    @ManyToMany()
    List<Tag> tags();

    @Formula(dependencies = "tags")
    default int tagCount() {
        return tags().size();
    }
}
```

Tag.java 从动方

```java
@Entity
public interface Tag extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id();

    @Key
    String name();

    @ManyToMany(mappedBy = "tags")
    List<Article> articleList();

    @Formula(dependencies = "articleList")
    default int articleCount() {
        return articleList().size();
    }
}
```

执行下列代码时出现错误

```Java
    public Page<Tag> getTagList(int pageIndex, int pageSize) {
        TagTable tagTable = Tables.TAG_TABLE;
        return sqlClient.createQuery(tagTable)
                .select(tagTable.fetch(
                        Fetchers.TAG_FETCHER
                                .name()
                                .articleCount() //计算属性
                ))
                .fetchPage(pageIndex, pageSize);
    }
```

异常信息：

**org.babyfish.jimmer.meta.ModelException: Illegal property "com.eedt.tag.Tag.articleCount", its dependency property "com.eedt.tag.Tag.articleList" must be scalar property or another formula property**
	at org.babyfish.jimmer.meta.impl.ImmutablePropImpl.createFormulaDependency(ImmutablePropImpl.java:1395)
	at org.babyfish.jimmer.meta.impl.ImmutablePropImpl.getDependenciesImpl(ImmutablePropImpl.java:1317)
	at org.babyfish.jimmer.meta.impl.ImmutablePropImpl.getDependencies(ImmutablePropImpl.java:1256)
	at org.babyfish.jimmer.sql.fetcher.impl.FetcherImpl.getFieldMap(FetcherImpl.java:240)
	at org.babyfish.jimmer.sql.ast.impl.table.FetcherSelectionImpl.accept(FetcherSelectionImpl.java:73)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.reselect(ConfigurableRootQueryImpl.java:120)
	at org.babyfish.jimmer.sql.ast.query.ConfigurableRootQuery.fetchUnlimitedCount(ConfigurableRootQuery.java:42)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.fetchPage(ConfigurableRootQueryImpl.java:65)
	at org.babyfish.jimmer.sql.ast.query.ConfigurableRootQuery.fetchPage(ConfigurableRootQuery.java:66)

**Comment by babyfish-ct** [comment]
Try `0.8.123`
