### ISSUE TITLE
[bug] Dynamic input for embeddable can't be saved

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#527]
```
@Embeddable
interface Nested {
...
}
```
```
dynamic input NestedInput {
  #allScalars
}
```

```
// nested received from controller

sql.update(MyEntity {
    id = 1
    this.nested = nested.toImmutable()
})
```

Exception is thrown:

```
java.lang.ClassCastException: class java.lang.Object cannot be cast to class org.babyfish.jimmer.runtime.ImmutableSpi (java.lang.Object is in module java.base of loader 'bootstrap'; org.babyfish.jimmer.runtime.ImmutableSpi is in unnamed module of loader 'app')
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChainedMutationItemImpl.collectItems(MutationItem.java:190) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChainedMutationItemImpl.expand(MutationItem.java:166) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.MutationItem.create(MutationItem.java:60) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.update(Saver.java:670) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:424) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveImpl(Saver.java:118) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:99) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:169) ~[jimmer-core-0.8.124.jar:na]
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42) ~[jimmer-core-0.8.124.jar:na]
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:102) ~[jimmer-core-0.8.124.jar:na]
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39) ~[jimmer-core-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:95) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:67) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28) ~[jimmer-spring-boot-starter-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:61) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:12) ~[jimmer-sql-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.save(KEntitiesImpl.kt:196) ~[jimmer-sql-kotlin-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.kt.KEntities.save$default(KEntities.kt:60) ~[jimmer-sql-kotlin-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.kt.KSqlClient.save(KSqlClient.kt:120) ~[jimmer-sql-kotlin-0.8.124.jar:na]
	at org.babyfish.jimmer.sql.kt.KSqlClient.update(KSqlClient.kt:131) ~[jimmer-sql-kotlin-0.8.124.jar:na]
```

**Comment by babyfish-ct** [comment]
The branch `dev` is committed, will be released ASAP.
