### ISSUE TITLE
[bug] In Kotlin mode, the generated property are inconsistent

### ISSUE THREAD

**Issue by flynndi** [babyfish-ct/jimmer#528]
```
@Entity
interface UserRole {

    @Id
    @GeneratedValue(generatorType = UUIdGenerator::class)
    val id: UUID

    val userId: String

    val roleId: String

    val deleteFlag: Boolean
}
```

```
{
    "id": "0C844055-A86E-94D9-2C50-77CAFBBC20AB",
    "userId": "12",
    "roleId": "213",
    "deleteFlag": false
}
```

Exception is thrown:
```
java.lang.IllegalArgumentException: There is no property "isDeleteFlag" in "io.quarkiverse.jimmer.it.entity.UserRole"
	at org.babyfish.jimmer.meta.impl.ImmutableTypeImpl.getProp(ImmutableTypeImpl.java:321)
	at org.babyfish.jimmer.jackson.ImmutableAnnotationIntrospector.findDeserializationConverter(ImmutableAnnotationIntrospector.java:104)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findDeserializationConverter(AnnotationIntrospectorPair.java:721)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findDeserializationConverter(AnnotationIntrospectorPair.java:722)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.findConvertingDeserializer(BeanDeserializerBase.java:813)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:548)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:315)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2450)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:771)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.doReadFrom(ServerJacksonMessageBodyReader.java:86)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:38)
	at io.quarkus.resteasy.reactive.jackson.runtime.serialisers.ServerJacksonMessageBodyReader.readFrom(ServerJacksonMessageBodyReader.java:77)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.readFrom(RequestDeserializeHandler.java:126)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:84)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:135)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by babyfish-ct** [comment]
Try `0.8.125`
