### ISSUE TITLE
How to deal with JavaEE Universal Response under kotlin

### ISSUE THREAD

**Issue by flynndi** [babyfish-ct/jimmer#530]
![1608802417](https://github.com/babyfish-ct/jimmer/assets/129767847/ad5efab1-96dc-4d26-a763-20db9e454cb8)

The problem seems to persist

_Originally posted by @flynndi in https://github.com/babyfish-ct/jimmer/issues/502#issuecomment-2041257137_

**Comment by babyfish-ct** [comment]
quarkus-jimmer-example-kt:integrationTest: Could not find io.github.flynndi:quarkus-jimmer-deployment:999-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/io/github/flynndi/quarkus-jimmer-deployment/999-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/io/github/flynndi/quarkus-jimmer-deployment/999-SNAPSHOT/quarkus-jimmer-deployment-999-SNAPSHOT.pom
  - file:/Users/chentao/.m2/repository/io/github/flynndi/quarkus-jimmer-deployment/999-SNAPSHOT/maven-metadata.xml
  - file:/Users/chentao/.m2/repository/io/github/flynndi/quarkus-jimmer-deployment/999-SNAPSHOT/quarkus-jimmer-deployment-999-SNAPSHOT.pom
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

有snapshot跑不起来

**Comment by babyfish-ct** [comment]
因为有错，你不想发布，但我也因此无法下载。

如果有错，请直接说出具体异常堆栈。

**Comment by flynndi** [comment]
implementation ("io.github.flynndi:quarkus-jimmer:0.0.1.CR11")
implementation ("io.github.flynndi:quarkus-jimmer-deployment:0.0.1.CR11")
ksp ("org.babyfish.jimmer:jimmer-ksp:0.8.121")

**Comment by flynndi** [comment]
RoutingContext failure (500): org.babyfish.jimmer.client.runtime.TypeResolvingException: Cannot resolve type via the chain: jakarta.ws.rs.core.Response@language -> java.util.Locale
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.collectProperties(StaticObjectTypeImpl.java:70)
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.init(StaticObjectTypeImpl.java:46)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.lambda$staticType$2(TypeContext.java:215)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.generic(TypeContext.java:149)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.staticType(TypeContext.java:214)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseNonNullType(TypeContext.java:133)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseType(TypeContext.java:88)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.operation(MetadataBuilder.java:287)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.service(MetadataBuilder.java:209)
	at org.babyfish.jimmer.client.runtime.impl.MetadataBuilder.build(MetadataBuilder.java:146)
	at io.quarkiverse.jimmer.runtime.client.Metadatas.create(Metadatas.java:48)
	at io.quarkiverse.jimmer.runtime.client.openapi.OpenApiHandler.handle(OpenApiHandler.java:47)
	at io.quarkiverse.jimmer.runtime.client.openapi.OpenApiHandler.handle(OpenApiHandler.java:33)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.babyfish.jimmer.client.runtime.TypeResolvingException: Cannot resolve type via the chain: java.util.Locale
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.init(StaticObjectTypeImpl.java:53)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.lambda$staticType$2(TypeContext.java:215)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.generic(TypeContext.java:149)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.staticType(TypeContext.java:214)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseNonNullType(TypeContext.java:133)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseType(TypeContext.java:88)
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.collectProperties(StaticObjectTypeImpl.java:65)
	... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: kotlin.Array
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.lambda$javaType$1(TypeContext.java:142)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.javaType(TypeContext.java:138)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.staticType(TypeContext.java:211)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseNonNullType(TypeContext.java:133)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.parseType(TypeContext.java:88)
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.collectProperties(StaticObjectTypeImpl.java:65)
	at org.babyfish.jimmer.client.runtime.impl.StaticObjectTypeImpl.init(StaticObjectTypeImpl.java:46)
	... 30 more
Caused by: java.lang.ClassNotFoundException: kotlin.Array
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.babyfish.jimmer.client.runtime.impl.TypeContext.lambda$javaType$1(TypeContext.java:140)
	... 37 more

**Comment by babyfish-ct** [comment]
Try `0.8.127`
