### ISSUE TITLE
[bug] Wrong readers order when selecting embeddable field as a @Formula result

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#536]
model:
```
@Entity
interface BookStore : LongId {

    @Version
    val version: Int

    val container: MyEmbeddable?

    @Formula(dependencies = ["container.nested"])
    val nested: MyEmbeddable2? get() = container?.nested

    val name: String

    val website: String?
}

@Embeddable
interface MyEmbeddable {
    val p1: Int?
    val nested: MyEmbeddable2
}

@Embeddable
interface MyEmbeddable2 {
    val p2: Int?
    val p3: Int?
}
```

dto:
```
BookStoreTestView {
  id
  name
  version
  nested
}
```

code:
```
sql.findById(BookStoreTestView::class, 1)
```

this throws exception:
```
Cannot produce immutable because an checked exception is raised in draft consumer lambda expression
org.babyfish.jimmer.DraftConsumerUncheckedException: Cannot produce immutable because an checked exception is raised in draft consumer lambda expression
	at app//org.babyfish.jimmer.DraftConsumerUncheckedException.rethrow(DraftConsumerUncheckedException.java:43)
	at app//org.babyfish.jimmer.sql.runtime.DynamicEmbeddedReader.read(DynamicEmbeddedReader.java:52)
	at app//org.babyfish.jimmer.sql.runtime.DynamicEmbeddedReader.read(DynamicEmbeddedReader.java:35)
	at app//org.babyfish.jimmer.sql.runtime.ObjectReader.read(ObjectReader.java:44)
	at app//org.babyfish.jimmer.sql.runtime.Selectors.lambda$select$0(Selectors.java:47)
	at app//org.babyfish.jimmer.runtime.Internal.usingSqlDraftContext(Internal.java:117)
	at app//org.babyfish.jimmer.sql.runtime.Selectors.lambda$select$1(Selectors.java:42)
	at app//org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:47)
	at app//org.babyfish.jimmer.sql.runtime.ExecutorForLog.simpleLog(ExecutorForLog.java:102)
	at app//org.babyfish.jimmer.sql.runtime.ExecutorForLog.execute(ExecutorForLog.java:42)
	at app//org.babyfish.jimmer.sql.runtime.Selectors.select(Selectors.java:31)
	at app//org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:252)
	at app//org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:237)
	at app//org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:26)
	at app//org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:469)
	at app//org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:237)
	at app//org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:176)
	at app//org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.lambda$findById$0(EntitiesImpl.java:116)
	at app//org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28)
	at app//org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:115)
	at app//org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.findById(KEntitiesImpl.kt:50)
	at app//org.babyfish.jimmer.sql.kt.KSqlClient.findById(KSqlClient.kt:102)
	
Caused by: org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "6" для параметра "columnIndex"
```

**Comment by belovaf** [comment]
And if I try to use flat with embeddables (that is what I really need), I get an error with the same model.

dto:
```
BookStoreTestView {
  id
  name
  version
  flat(container) {
    nested
  }
}
```

Compiler error:
```
Type mismatch: inferred type is Unit! but MyEmbeddable2! was expected
```
