### ISSUE TITLE
[bug] DTO with @Formula and @Embeddable properties can cause UnloadedException

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#539]
Model
```
@Entity
interface MyEntity : LongId {
    val container1: MyEmbeddable1?
    val container2: MyEmbeddable2?

    @Formula(dependencies = ["container1.p1", "container1.p2"])
    val sum1: Int? get() = (container1?.p1 ?: 0) + (container1?.p2 ?: 0)

    @Formula(dependencies = ["container2.p3", "container2.p4"])
    val sum2: Int? get() = (container2?.p3 ?: 0) + (container2?.p4 ?: 0)

    @Formula(dependencies = ["sum1", "sum2"])
    val totalSum: Int?
        get() {
            val s1 = sum1 ?: return null
            val s2 = sum2 ?: return null
            return s1 + s2
        }
}

@Embeddable
interface MyEmbeddable1 {
    val p1: Int?
    val p2: Int?
}

@Embeddable
interface MyEmbeddable2 {
    val p3: Int?
    val p4: Int?
}
```

DTO:
```
MyEntityView {
  id
  totalSum
  flat(container1) {
    p1
  }
}
```

Code:
```
sql.findById(MyEntityView::class, 1)
```

Generated sql:
```
select tb_1_.ID, tb_1_.P1 from MY_ENTITY tb_1_ where tb_1_.ID = ?
```

Stacktrace:
```
The property "example.model.MyEntity.container2" is unloaded
org.babyfish.jimmer.UnloadedException: The property "example.model.MyEntity.container2" is unloaded
	at example.model.MyEntityDraft$$$Impl.getContainer2(MyEntityDraft.kt:259)
	at example.model.MyEntity.getSum2(MyEntity.kt:25)
	at example.model.MyEntity.getTotalSum(MyEntity.kt:31)
	at example.model.dto.MyEntityView.<init>(MyEntityView.kt:36)
	at example.model.dto.MyEntityView.METADATA$lambda$0(MyEntityView.kt:82)
	at org.babyfish.jimmer.sql.fetcher.impl.FetcherUtil.fetch(FetcherUtil.java:88)
	at org.babyfish.jimmer.sql.runtime.Selectors.select(Selectors.java:56)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:252)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:237)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:26)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:469)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:237)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:176)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.lambda$findById$0(EntitiesImpl.java:116)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:115)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.findById(KEntitiesImpl.kt:50)
	at org.babyfish.jimmer.sql.kt.KSqlClient.findById(KSqlClient.kt:102)
```

**Comment by belovaf** [comment]
Looks like the expression
```
flat(container1) {
  p1
}
```
erroneously removes all dependencies of the `totalSum` property.

**Comment by babyfish-ct** [comment]
Try `0.8.128`
