### ISSUE TITLE
广义乐观锁报错

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#557]
代码：
Book book = sqlClient.getEntities().findById(Book.class, 1L);
sqlClient.getEntities().saveCommand(book).setOptimisticLock(BookTable.class, (table, it) -> {
    return table.tenant().eq("1");
}).execute();

堆栈：
Exception in thread "main" org.babyfish.jimmer.sql.runtime.SaveException$OptimisticLockError: Save error caused by the path: "<root>": Cannot update the entity whose type is "org.babyfish.jimmer.sql.example.model.Book" and id is "1" when using optimistic lock
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.update(Saver.java:706)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:432)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveImpl(Saver.java:118)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:99)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:169)
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42)
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:102)
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:95)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:67)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:48)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:12)

<img width="718" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/38320937/619517f4-211e-4558-bc46-ff0764ac57c7">

这里version为null

**Comment by babyfish-ct** [comment]
Try `0.8.130`
