### ISSUE TITLE
[Bug] Boolean name starting with 'is' in Entity

### ISSUE THREAD

**Issue by moeshin** [babyfish-ct/jimmer#579]
```kt
@Entity
interface XXX {
    // ...
    val isDeleted: Boolean
}
```

```text
java.lang.IllegalArgumentException: There is no property "deleted" in "XXX"
    at org.babyfish.jimmer.meta.impl.ImmutableTypeImpl.getProp(ImmutableTypeImpl.java:323)
    at org.babyfish.jimmer.jackson.ImmutableSerializerModifier.changeProperties(ImmutableSerializerModifier.java:36)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:415)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:295)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:240)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
    at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1525)
    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
    at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:739)
    at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer._findCachedSerializer(ReferenceTypeSerializer.java:470)
    at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:384)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:422)
    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1570)
    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)
    ....
```

https://github.com/babyfish-ct/jimmer/blob/4ec3f213cfbc4d2bde17cbc72e77ecf88df68ac7/project/jimmer-core/src/main/java/org/babyfish/jimmer/impl/util/StringUtil.java#L75-L77

**Comment by babyfish-ct** [comment]
Try `0.8.134`
