### ISSUE TITLE
[Bug] jackson序列化实体异常

### ISSUE THREAD

**Issue by LoptrX** [babyfish-ct/jimmer#580]
版本：
0.8.132-0.8.133

问题：
jimmer jackson module 对实体序列化时出现反射 filed 强转 method 的情况

Caused by: java.lang.ClassCastException: class java.lang.reflect.Field cannot be cast to class java.lang.reflect.Method (java.lang.reflect.Field and java.lang.reflect.Method are in module java.base of loader 'bootstrap')
	at org.babyfish.jimmer.jackson.ImmutableSerializerModifier.changeProperties(ImmutableSerializerModifier.java:30) ~[jimmer-core-0.8.133.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:415) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:295) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:240) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1503) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1451) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:556) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:834) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:307) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3987) ~[jackson-databind-2.15.4.jar:2.15.4]
	at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.serialize(Jackson2JsonRedisSerializer.java:155) ~[spring-data-redis-3.2.5.jar:3.2.5]
	... 83 common frames omitted

**Comment by babyfish-ct** [comment]
Try `0.8.134`
