### ISSUE TITLE
Race condition during client initialization

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#591]
I found very specific case while testing parallel run. It can be reproduced by the following code:
```kotlin
   @Test
    fun `create clients in multiple threads`() {
        val service = Executors.newCachedThreadPool()
        var count = 10
        while (count -- > 0) {
            service.execute {
                while (!Thread.currentThread().isInterrupted) {
                    newKSqlClient {}
                }
            }
        }
    }
```
The critical section is `ImmutablePropImpl.getMappedBy` method - multiple threads can process the same property at the same time. As a result, exception would be thrown:
```
Exception in thread "pool-1-thread-7" org.babyfish.jimmer.meta.ModelException: Both `org.babyfish.jimmer.sql.kt.model.TreeNode.childNodes` and `org.babyfish.jimmer.sql.kt.model.TreeNode.childNodes` use `mappedBy` to reference `org.babyfish.jimmer.sql.kt.model.TreeNode.parent`
	at org.babyfish.jimmer.meta.impl.ImmutablePropImpl.acceptMappedBy(ImmutablePropImpl.java:1205)
	at org.babyfish.jimmer.meta.impl.ImmutablePropImpl.getMappedBy(ImmutablePropImpl.java:1174)
	at org.babyfish.jimmer.sql.runtime.EntityManager.<init>(EntityManager.java:122)
	at org.babyfish.jimmer.sql.runtime.EntityManager.fromResources(EntityManager.java:232)
```

A possible solution:
```
ImmutablePropImpl:1204
< if (acceptedMappedBy != null) {
> if (acceptedMappedBy != null && acceptedMappedBy != prop) {
```

**Comment by babyfish-ct** [comment]
Workaround: Add lock

**Comment by babyfish-ct** [comment]
Try `0.8.137`
