### ISSUE TITLE
【集合关联】使用TableEx进行集合关联查询时where联表主外键字段拼接错乱

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#598]
# 版本信息
- jimmer:   0.8.135 ~ 0.8.139
- koltin:  2.0.0
- gradle：8.8
- springboot：2.7.18  or 3.3.1

## 特别说明

是我项目的旧有功能，使用了集合关联查询TableEx，我之前使用 0.8.131版本，今日升级139版本发现了有问题，均未改动代码

重新测试了 131 ~ 139版本发现

0.8.134以前的版本是正常的，0.8.135 ~ 0.8.139之后才有问题 应该是一个高版本才有的问题

# 问题描述

我有一个菜单、角色、用户的关联关系，如下：
<img width="489" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/eccf062f-471a-4981-a80d-2be1cf5725c4">

其中 所有表中主键id名称均为id，外键关联xxx_id  例如  user表id  在role表当中外键为 user_id
 jimmer关联关系：

- Menu：

```kotlin
interface SysMenuRelation {

//只展示关联关系
    @ManyToMany
    @JoinTable(
        //中间表表名 表名要跟数据库名一致 区分大小写
        name = "sys_role_menu",
        // 中间表指向当前实体的外键的列名
        joinColumnName = "menu_id",
        //中间表指向关联实体的外键的列名
        inverseJoinColumnName = "role_id"
    )
    val sysRoles: List<SysRole>

    @IdView("sysRoles")
    val roleIds: List<Long>
}
```

- Role
```kotlin
interface SysRoleRelation {

    /** 一个角色拥有多个菜单权限 */
    @ManyToMany(mappedBy = "sysRoles")
    val sysMenus: List<SysMenu>


    @ManyToMany
    @JoinTable(
//        中间表表名
        name = "sys_user_role",
//         中间表指向当前实体的外键的列名
        joinColumnName = "role_id",
//        中间表指向关联实体的外键的列名
        inverseJoinColumnName = "user_id"
    )
    val sysUsers: List<SysUser>


    /**  */
    @IdView("sysUsers")
    val userIds: List<Long>

    @IdView("sysMenus")
    val menuIds: List<Long>

}
```

- User
```kotlin
@MappedSuperclass
interface SysUserRelation {
// `mappedBy`表示`SysUser.roles`
    // 是`Book.authors`的镜像
    @ManyToMany(mappedBy = "sysUsers")
    val sysRoles: List<SysRole>

    @IdView(value = "sysRoles")
    val roleIds: List<Long>
}
```

## 需求：

通过 用户id 查找他所拥有的菜单集合

### 使用TableEx

```kotlin
sql.createQuery(SysMenu::class) {
    where(
        table.asTableEx().sysRoles.sysUsers.id.valueIn(userIds),  // 主要是这一句
        menuType?.let {
            table.type eq menuType
        }
    )
    sort?.takeIf { it.isSorted }?.let {
        orderBy(it)
    } ?: orderBy(table.sortValue.asc(), table.id.asc())
    select(table.fetch(fetcher))
}.execute()

```

- 134以前版本正确sql:

```sql
SQL: select
    tb_1_.id // 省略其他字段 都是查询tb_1_也就是Menu表的内容 没有其他关联表字段
 
from sys_menu tb_1_
inner join sys_role_menu tb_2_
    on tb_1_.id = tb_2_.menu_id
inner join sys_role tb_3_
    on tb_2_.role_id = tb_3_.id
inner join sys_user_role tb_4_
    on tb_3_.id = tb_4_.role_id
inner join sys_user tb_5_                          //  tb_5_是 USER表
    on tb_4_.user_id = tb_5_.id
where
        tb_5_.id = 1645607078095486976   // 这里是正确的user表的id的字段 id的值
    and
        tb_1_.deleted <> 1
    and
        tb_5_.deleted <> 1
    and
        tb_3_.deleted <> 1
order by
    tb_1_.sort_value asc,
    tb_1_.id asc

```

- 135 ~ 139版本
```sql
SQL: select
    tb_1_.id // 省略其他字段 都是查询tb_1_也就是Menu表的内容 没有其他关联表字段
from sys_menu tb_1_
inner join sys_role_menu tb_2_
    on tb_1_.id = tb_2_.menu_id
inner join sys_role tb_3_
    on tb_2_.role_id = tb_3_.id
inner join sys_user_role tb_4_
    on tb_3_.id = tb_4_.role_id
inner join sys_user tb_5_            //  tb_5_是 USER表
    on tb_4_.user_id = tb_5_.id
where
        tb_5_.user_id = 1645607078095486976   // 主要是这里 识别成了 外键名称 user_id
    and
        tb_1_.deleted <> 1
    and
        tb_5_.deleted <> 1
    and
        tb_3_.deleted <> 1
order by
    tb_1_.sort_value asc,
    tb_1_.id asc

```
<img width="1567" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/a16edf5b-4f45-4246-878b-747777dbc46c">

报错： 

```bash
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'tb_5_.user_id' in 'where clause'

```

详细的日志 截取了jimmer代码的错误栈 其他忽略了：
```bash

Caused by: org.babyfish.jimmer.sql.runtime.ExecutionException: Cannot execute SQL statement: select
    tb_1_.id // 省略其他字段 都是查询tb_1_也就是Menu表的内容 没有其他关联表字段
from sys_menu tb_1_
inner join sys_role_menu tb_2_
    on tb_1_.id = tb_2_.menu_id
inner join sys_role tb_3_
    on tb_2_.role_id = tb_3_.id
inner join sys_user_role tb_4_
    on tb_3_.id = tb_4_.role_id
inner join sys_user tb_5_
    on tb_4_.user_id = tb_5_.id
where
        tb_5_.user_id = ?
    and
        tb_1_.deleted <> ?
    and
        tb_5_.deleted <> ?
    and
        tb_3_.deleted <> ?
order by
    tb_1_.sort_value asc,
    tb_1_.id asc, variables: [1645607078095486976, 1, 1, 1]
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:33)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.prettyLog(ExecutorForLog.java:124)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.execute(ExecutorForLog.java:42)
	at org.babyfish.jimmer.sql.runtime.Selectors.select(Selectors.java:31)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:252)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:28)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:242)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:26)
	at org.babyfish.jimmer.sql.kt.ast.query.impl.KTypedRootQueryImpl.execute(KTypedRootQueryImpl.kt:27)
	at org.babyfish.jimmer.sql.kt.ast.query.impl.KTypedRootQueryImpl.execute(KTypedRootQueryImpl.kt:7)
	at org.babyfish.jimmer.sql.kt.ast.KExecutable.execute$default(KExecutable.kt:6)
	at org.xxx.web.repository.SysMenuRepository$DefaultImpls.listByUserIds(SysMenuRepository.kt:89)
```

### 方法二: 修改代码   使用子查询 

```kotlin
sql.createQuery(SysMenu::class) {
    where += table.sysRoles { sysUsers { id valueIn userIds } }
    menuType?.let { where += table.type.eq(menuType) }
    sort?.takeIf { it.isSorted }?.let {
        orderBy(it)
    } ?: orderBy(table.sortValue.asc(), table.id.asc())
    select(table.fetch(fetcher))
}.execute()

```

子查询是正常的返回了期望数据
```sql
select
    tb_1_.id // 省略其他字段 都是查询tb_1_也就是Menu表的内容 没有其他关联表字段
from sys_menu tb_1_
where
        exists(
            select
                1
            from sys_role tb_2_
            inner join sys_role_menu tb_3_
                on tb_2_.id = tb_3_.role_id
            where
                    tb_3_.menu_id = tb_1_.id
                and
                    exists(
                        select
                            1
                        from sys_user tb_5_
                        inner join sys_user_role tb_6_
                            on tb_5_.id = tb_6_.user_id
                        where
                                tb_6_.role_id = tb_2_.id
                            and
                                tb_5_.id = 1645607078095486976
                            and
                                tb_5_.deleted <> 1
                    )
                and
                    tb_2_.deleted <> 1
        )
    and
        tb_1_.deleted <> 1
order by
    tb_1_.sort_value asc,
    tb_1_.id asc
```

大部分TableEx应该可以使用子查询代替，由于是老项目，之前就使用了TableEx，不过TableEx还是有场景能够使用的，烦请大佬看下🙏🏻

**Comment by qinkangdeid** [comment]
[aikero-web-app.zip](https://github.com/user-attachments/files/16096903/aikero-web-app.zip)
这个包是能够复现的包

**Comment by qinkangdeid** [comment]
很奇怪 我本想最小复现一下  弄了个新工程  然后运行的时候 其实查不到tb5  我还在查找不同 
[sb3.zip](https://github.com/user-attachments/files/16096986/sb3.zip)

**Comment by qinkangdeid** [comment]
> 很奇怪 我本想最小复现一下 弄了个新工程 然后运行的时候 其实查不到tb5 我还在查找不同 这个是之查询到tb4的例子 [sb3.zip](https://github.com/user-attachments/files/16096986/sb3.zip)
> 
> <img alt="a89cbf0e5d059938ff6d1352ec52a2eb" width="375" src="https://private-user-images.githubusercontent.com/17582522/345788797-e4b00a2c-a09c-4ede-85bd-dc121736163a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA4NjcsIm5iZiI6MTcyMDA5MDU2NywicGF0aCI6Ii8xNzU4MjUyMi8zNDU3ODg3OTctZTRiMDBhMmMtYTA5Yy00ZWRlLTg1YmQtZGMxMjE3MzYxNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhODkxOGY4MWRmYzY3YjhkN2E5YzMzNzVlNDg5Y2QyY2VhMjU5YWZiN2MwYzkyNmI4ODM2OGI3NjBlZGYyM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXw9iRkuaLKBCm_SM8Ymo28UrSkPBaDiV8x12vNJ1kA">

这里有一个重大的差异就是没有逻辑删除字段  所以经过了sql优化 没有查询到tb5

**Comment by qinkangdeid** [comment]
这个是最纯净的复现包  加了逻辑删除字段 
[sb3-with-logic-delete.zip](https://github.com/user-attachments/files/16097751/sb3-with-logic-delete.zip)



<img width="764" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/16aea1ab-5a9b-45e8-8724-de8cc0c717fa">

**Comment by babyfish-ct** [comment]
Try `0.8.140`
