### ISSUE TITLE
class cast on kotlin native expression

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#606]
native expression looks like:
```kotlin
fun <T : Any> KExpression<List<T>>.overlap(values: Array<T>): KNonNullExpression<Boolean> {
    val expression = this
    return sql(Boolean::class, "%e && array[%v]") {
        value(values)
        expression(expression)
    }
}
```

fails with:
```
Caused by: java.lang.ClassCastException: class org.babyfish.jimmer.sql.kt.ast.expression.impl.NonNullNativeExpression cannot be cast to class org.babyfish.jimmer.sql.ast.Predicate (org.babyfish.jimmer.sql.kt.ast.expression.impl.NonNullNativeExpression and org.babyfish.jimmer.sql.ast.Predicate are in unnamed module of loader 'app')
	at org.babyfish.jimmer.sql.kt.ast.expression.impl.AndPredicate.onResolveVirtualPredicate(LogicPredicate.kt:128)
	at org.babyfish.jimmer.sql.kt.ast.expression.impl.AbstractKExpression.resolveVirtualPredicate(AbstractKExpression.kt:55)
	at org.babyfish.jimmer.sql.ast.impl.AstContext.resolveVirtualPredicate(AstContext.java:130)
	at org.babyfish.jimmer.sql.ast.impl.AstContext.resolveVirtualPredicates(AstContext.java:153)
	at org.babyfish.jimmer.sql.ast.impl.AbstractMutableStatementImpl.resolveVirtualPredicate(AbstractMutableStatementImpl.java:204)
	at org.babyfish.jimmer.sql.ast.impl.AbstractMutableStatementImpl.applyVirtualPredicates(AbstractMutableStatementImpl.java:245)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.preExecute(ConfigurableRootQueryImpl.java:309)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:251)
```
![image](https://github.com/user-attachments/assets/3a4adc76-2237-44d9-9188-ef95537e369b)

**Comment by babyfish-ct** [comment]
Try `0.8.149`
