### ISSUE TITLE
class cast on negation of the expression `exists`

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#607]
The predicate is: 
```kotlin
where(table.authors { lastName.isNotNull() }?.not())
```
`table.authors` is auto generated function:
```kotlin
public
        fun KProps<BookModel>.authors(block: KNonNullTableEx<AuthorModel>.() -> KNonNullExpression<Boolean>?):
        KNonNullExpression<Boolean>? = exists(BookModelProps.AUTHORS.unwrap(), block)
```
fails with:
```
Caused by: java.lang.ClassCastException: class org.babyfish.jimmer.sql.ast.impl.associated.VirtualPredicateMergedResult cannot be cast to class org.babyfish.jimmer.sql.kt.ast.expression.KNonNullExpression (org.babyfish.jimmer.sql.ast.impl.associated.VirtualPredicateMergedResult and org.babyfish.jimmer.sql.kt.ast.expression.KNonNullExpression are in unnamed module of loader 'app')
	at org.babyfish.jimmer.sql.kt.ast.expression.impl.NotPredicate.onResolveVirtualPredicate(LogicPredicate.kt:113)
	at org.babyfish.jimmer.sql.kt.ast.expression.impl.AbstractKExpression.resolveVirtualPredicate(AbstractKExpression.kt:55)
	at org.babyfish.jimmer.sql.ast.impl.AstContext.resolveVirtualPredicate(AstContext.java:130)
	at org.babyfish.jimmer.sql.ast.impl.AstContext.resolveVirtualPredicates(AstContext.java:153)
	at org.babyfish.jimmer.sql.ast.impl.AbstractMutableStatementImpl.resolveVirtualPredicate(AbstractMutableStatementImpl.java:204)
	at org.babyfish.jimmer.sql.ast.impl.AbstractMutableStatementImpl.applyVirtualPredicates(AbstractMutableStatementImpl.java:245)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.preExecute(ConfigurableRootQueryImpl.java:309)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:251)
```

**Comment by babyfish-ct** [comment]
Try `0.8.149`
