### ISSUE TITLE
多模块项目启动时 `EntityManager.combine` 报错：`is not entity`

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#62]
报错日志：
```
Caused by: java.lang.IllegalArgumentException: "io.github.AbstractEntity" is not entity
	at org.babyfish.jimmer.sql.runtime.EntityManager.<init>(EntityManager.java:35)
	at org.babyfish.jimmer.sql.runtime.EntityManager.combine(EntityManager.java:108)
	at io.elva.server.config.JimmerConfiguration.entityManager(JimmerConfiguration.kt:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 48 common frames omitted

```

项目为多模块，因此在配置`jimmer`时使用了`EntityManager.combine`，`combine`函数在最后进行类注册时，没有过滤掉非 `@Entity`注解的类
https://github.com/babyfish-ct/jimmer/blob/cd61baa0b6e439a73e0211157876e1b56ffaff74/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/EntityManager.java#L103-L108
```kotlin
@Bean
fun entityManager(): EntityManager {
    return EntityManager.combine(
        io.github.core.domain.ENTITY_MANAGER,
        io.github.user.domain.ENTITY_MANAGER
    )
}

// entity 基本公共类
@MappedSuperclass
interface AbstractEntity {
    val createTime: LocalDateTime

    val updateTime: LocalDateTime

    val createBy: String?

    val updateBy: String?
}

// entity
@Table(name = "sys_api_access_log")
@Entity
interface ApiAccessLog : AbstractEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long
    val userId: Long?

    ... ...
}

```

**Comment by babyfish-ct** [comment]
Try 0.7.45
