### ISSUE TITLE
deleteCommand - IllegalArgumentException - is not managed by current EntityManager

### ISSUE THREAD

**Issue by Thorben91** [babyfish-ct/jimmer#639]
Hi everyone, I just started my first project with jimmer, so I'm not sure if I'm making a mistake, missing something or there is a bug with jimmer.
I have two entities “FieldGroup” and “FieldDefinition”, now when I have created a FieldGroup with multiple FieldDefinitions and then try to delete a FieldDefinition, I get an exception “java.lang.IllegalArgumentException: ‘com.example.app.persistence.entities.FieldDefinition’ is not managed by current EntityManager”. Why is this, what am I doing wrong or what have I misunderstood?
Here is my code:

**BaseEntity.java**
```java
package com.example.app.persistence.entities;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.UUID;

import org.babyfish.jimmer.sql.GeneratedValue;
import org.babyfish.jimmer.sql.Id;
import org.babyfish.jimmer.sql.MappedSuperclass;
import org.babyfish.jimmer.sql.meta.UUIDIdGenerator;

import com.fasterxml.jackson.annotation.JsonFormat;

@MappedSuperclass
public interface BaseEntity extends Serializable {

	@Id
	@GeneratedValue(generatorType = UUIDIdGenerator.class)
	UUID id();

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss.SSSZ")
	ZonedDateTime created();

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss.SSSZ")
	ZonedDateTime lastModified();
}
```
**FieldGroup.java**
```java
package com.example.app.persistence.entities;

import java.util.List;

import org.babyfish.jimmer.sql.Entity;
import org.babyfish.jimmer.sql.Key;
import org.babyfish.jimmer.sql.KeyUniqueConstraint;
import org.babyfish.jimmer.sql.OneToMany;
import org.babyfish.jimmer.sql.OrderedProp;

@Entity
@KeyUniqueConstraint
public interface FieldGroup extends BaseEntity {

	@Key
	String name();

	String label();

	@OneToMany(mappedBy = "fieldGroup", orderedProps = {@OrderedProp("name")})
	List<FieldDefinition> fieldDefinitions();
}
```
**FieldDefinition.java**
```java
package com.example.app.persistence.entities;

import java.io.Serializable;

import org.babyfish.jimmer.sql.Entity;
import org.babyfish.jimmer.sql.ForeignKeyType;
import org.babyfish.jimmer.sql.JoinColumn;
import org.babyfish.jimmer.sql.Key;
import org.babyfish.jimmer.sql.KeyUniqueConstraint;
import org.babyfish.jimmer.sql.ManyToOne;

import com.example.app.persistence.enums.FieldType;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

@Entity
@KeyUniqueConstraint
public interface FieldDefinition extends BaseEntity {

	@Key
	String name();

	FieldType type();

	String label();

	@Nullable
	Serializable defaultValue();

	@Nullable
	Serializable placeholder();

	@Nonnull
	@ManyToOne
	@JoinColumn(foreignKeyType = ForeignKeyType.REAL)
	FieldGroup fieldGroup();
}
```
**deleteTest()**
```java
private final void deleteTest() {
	final var fieldGroup = Objects.createFieldGroup(draft -> draft.setName("field_group_%s".formatted(RandomStringUtils.randomAlphanumeric(6)))
			.setLabel("Field Group 1")
			.setFieldDefinitions(new ArrayList<>()));

	final var insertedFieldGroup = sqlClient.insert(fieldGroup)
			.getModifiedEntity();

	final var fieldGroupId = insertedFieldGroup.id();

	final var fieldDefinition1 = Objects.createFieldDefinition(draft -> draft.setName("field_definition_%s".formatted(RandomStringUtils.randomAlphanumeric(6)))
			.setType(FieldType.STRING)
			.setLabel("Field Definition 1")
			.setDefaultValue(null)
			.setPlaceholder(null)
			.setFieldGroup(ImmutableObjects.makeIdOnly(FieldGroup.class, fieldGroupId)));
	final var insertedFieldDefinition1 = sqlClient.insert(fieldDefinition1)
			.getModifiedEntity();
	final var insertedFieldDefinitionId1 = insertedFieldDefinition1.id();

	final var fieldDefinition2 = Objects.createFieldDefinition(draft -> draft.setName("field_definition_%s".formatted(RandomStringUtils.randomAlphanumeric(6)))
			.setType(FieldType.STRING)
			.setLabel("Field Definition 2")
			.setDefaultValue(null)
			.setPlaceholder(null)
			.setFieldGroup(ImmutableObjects.makeIdOnly(FieldGroup.class, fieldGroupId)));
	final var insertedFieldDefinition2 = sqlClient.insert(fieldDefinition2)
			.getModifiedEntity();
	final var insertedFieldDefinitionId2 = insertedFieldDefinition2.id();

	final var updatedFieldGroup = Objects.createFieldGroup(insertedFieldGroup, draft -> {
		draft.fieldDefinitions()
				.add(ImmutableObjects.makeIdOnly(FieldDefinition.class, insertedFieldDefinitionId1));
		draft.fieldDefinitions()
				.add(ImmutableObjects.makeIdOnly(FieldDefinition.class, insertedFieldDefinitionId2));
	});

	sqlClient.save(updatedFieldGroup);

	final var deleteResult = sqlClient.getEntities()
			.deleteCommand(FieldDefinition.class, insertedFieldDefinitionId1, DeleteMode.PHYSICAL)
			.configure(cfg -> cfg.setDissociateAction(FieldDefinitionProps.FIELD_GROUP, DissociateAction.NONE))
			.execute(); // <-- This line is throwing the excpetion.
	System.out.println(deleteResult);
}
```

**Exception**
```
java.lang.IllegalArgumentException: "com.example.app.persistence.entities.FieldDefinition" is not managed by current EntityManager
     at org.babyfish.jimmer.sql.runtime.EntityManager.info(EntityManager.java:294)
     at org.babyfish.jimmer.sql.runtime.EntityManager.getDissociationInfo(EntityManager.java:268)
     at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.preHandle(Deleter.java:126)
     at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.preHandle(Deleter.java:117)
     at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.execute(Deleter.java:101)
     at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.execute(Deleter.java:95)
     at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.executeImpl(DeleteCommandImpl.java:93)
     at com.example.app.persistence.JimmerConnectionManager.execute(JimmerConnectionManager.java:27)
     at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:80)
     at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:18)
     at org.babyfish.jimmer.sql.ast.Executable.execute(Executable.java:12)
     at com.example.app.pages.HomePage.deleteTest(HomePage.java:121)
     at com.example.app.pages.HomePage.<init>(HomePage.java:55)
     at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:171)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:76)
     at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:90)
     at org.apache.wicket.core.request.handler.PageProvider$Provision.getPage(PageProvider.java:369)
     at org.apache.wicket.core.request.handler.PageProvider.getPageInstance(PageProvider.java:170)
     at org.apache.wicket.request.handler.render.PageRenderer.getPage(PageRenderer.java:78)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:231)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:910)
     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307)
     at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
     at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
     at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:181)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
     at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
     at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
     at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
     at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:70)
     at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
     at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
     at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
     at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
     at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
     at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
     at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
     at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:740)
     at org.eclipse.jetty.server.handler.SecuredRedirectHandler.handle(SecuredRedirectHandler.java:93)
     at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:858)
     at org.eclipse.jetty.server.Server.handle(Server.java:181)
     at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
     at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
     at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:574)
     at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:390)
     at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:150)
     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
     at java.base/java.lang.Thread.run(Thread.java:1583)
```

Thank you and best regards
Thorben

**Comment by babyfish-ct** [comment]
The delete/deleteCommand accept `id`/`ids`, not `entity/entities`

> BTW, `@ KeyUniqueConstraint` is new annotation in my newest huge refactor(let save-command uses upsert abliity of database and apply batch sql for every level of the tree), I will be published a few days later, but now it is not published, why can it be used?

**Comment by Thorben91** [comment]
Thanks for the quick reply. Yes, I know, I am also passing the id and not the entity. Here is the Code:
```java
final var insertedFieldDefinitionId1 = insertedFieldDefinition1.id();
```
and
```java
final var deleteResult = sqlClient.getEntities()
		.deleteCommand(FieldDefinition.class, insertedFieldDefinitionId1, DeleteMode.PHYSICAL)
		.configure(cfg -> cfg.setDissociateAction(FieldDefinitionProps.FIELD_GROUP, DissociateAction.NONE))
		.execute(); // <-- This line is throwing the excpetion.
```
That should be correct, right?

**@KeyUniqueConstraint**
I am using the latest version of maven central, the annotation is available there. Here is the link:
[https://central.sonatype.com/artifact/org.babyfish.jimmer/jimmer-sql/0.8.157](https://central.sonatype.com/artifact/org.babyfish.jimmer/jimmer-sql/0.8.157)

best regards
Thorben

**Comment by babyfish-ct** [comment]
After compilation, there will be generated source file `META-INF/jimmer/entities` in the sub project that defines entity interface. 

Please view whether all entity interfaces are declared in the list of this file.

**Comment by Thorben91** [comment]
Yes, the file ist there and it contains both interfaces, here is the file content:
```
com.example.app.persistence.entities.FieldDefinition
com.example.app.persistence.entities.FieldGroup
```

I start the project via Eclipse (SpringTools 4), is there a way to check if the `META-INF/jimmer/entities` file is found and loaded correctly at runtime?

best regards
Thorben

**Comment by babyfish-ct** [comment]
Yes, this small file is loaded runtime, aovid to scan all packages like spring.

If there are still some problem, please close the mulitple-class-loader tools such as spring-dev-tools

Too many task, no time to fight with multiple-class-loader solutions.

**Comment by Thorben91** [comment]
Thanks for the support, your answer has led me to a solution.
It was not a classloader problem, but it seems to be an Eclipse-Maven-Plugin problem, when I compile and start my application via Eclipse, all classes are created by the AnnotationProcessor, but the file `META-INF/jimmer/entities` is missing, I can't tell at the moment if it is not created or deleted again. If I do the whole thing without Eclipse only with Maven via commandline, everything works.

My solution for now is:
```java
JSqlClient.newBuilder().setEntityManager(new EntityManager(FieldGroup.class, FieldDefinition.class));
```

Maybe it will help others in the future.

Perhaps a warning or debug message would be helpful here if the file `META-INF/jimmer/entities` could not be loaded or `urls` is empty:
[https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/EntityManager.java#L198](https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/EntityManager.java#L198)

Or if `classes` is empty:
[https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/EntityManager.java#L232](https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/EntityManager.java#L232)

So that the developer can recognize such problems at an early stage.

**And jimmer is a great project, good work!**


best regards
Thorben

**Comment by babyfish-ct** [comment]
0.8.158 Released

The most important and complex upgrade in Jimmer's history. The functionality of the save-command is basically consistent with the current old documentation, but the entire implementation mechanism of the save command has been recreated, and the SQL generated behind the scenes is completely different. This is the first version of the new save-command (documentation synchronization will be completed in the coming weeks).

If a select query is issued during the execution of the save command, the SQL log will print something called QueryReason, which is very important for optimizing applications.
