### ISSUE TITLE
[bug] Failed to append an entity

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#646]
java.lang.NullPointerException: Cannot invoke "org.babyfish.jimmer.meta.ImmutableProp.getAnnotation(java.lang.Class)" because the return value of "org.babyfish.jimmer.sql.runtime.MutationPath.getProp()" is null
	at org.babyfish.jimmer.sql.ast.impl.mutation.MutationContext.throwNullTarget(MutationContext.java:164)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.savePostAssociation(Saver.java:192)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveAllImpl(Saver.java:116)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:48)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:173)
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42)
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:102)
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:44)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:45)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:37)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:16)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.save(KEntitiesImpl.kt:199)
	at org.babyfish.jimmer.sql.kt.KEntities.save$default(KEntities.kt:60)
	at org.babyfish.jimmer.sql.kt.KSqlClient.save(KSqlClient.kt:125)
	at org.babyfish.jimmer.sql.kt.KSqlClient.append(KSqlClient.kt:189)
	at org.babyfish.jimmer.sql.kt.KSqlClient.append$default(KSqlClient.kt:188)

**Comment by babyfish-ct** [comment]
What is the code of saving, what is the data structure?

**Comment by babyfish-ct** [comment]
Try `0.8.159`
