### ISSUE TITLE
[BUG] batchDelete sql 字段名问题

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#650]
抱歉这个bug没法简单复现，下面先附上调用栈，推测应该是sqlBuilder有一个tb_1.使用错成字段名：

```
Cannot create the batch SQL statement: delete from jimmer_code_gen.gen_super_entity_mapping tb_1_ where exists (select * from jimmer_code_gen.gen_entity tb_2_ where tb_1_.inherit_entity_id = tb_2_.id and idid = ?)
org.babyfish.jimmer.sql.runtime.ExecutionException: Cannot create the batch SQL statement: delete from jimmer_code_gen.gen_super_entity_mapping tb_1_ where exists (select * from jimmer_code_gen.gen_entity tb_2_ where tb_1_.inherit_entity_id = tb_2_.id and idid = ?)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor$BatchContextImpl.<init>(DefaultExecutor.java:128)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.executeBatch(DefaultExecutor.java:55)
	at org.babyfish.jimmer.sql.ast.impl.mutation.AbstractOperator.executeImpl(AbstractOperator.java:74)
	at org.babyfish.jimmer.sql.ast.impl.mutation.AbstractOperator.execute(AbstractOperator.java:51)
	at org.babyfish.jimmer.sql.ast.impl.mutation.MiddleTableOperator.disconnect(MiddleTableOperator.java:504)
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChildTableOperator.disconnect(ChildTableOperator.java:192)
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChildTableOperator.disconnect(ChildTableOperator.java:114)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.execute(Deleter.java:152)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.executeImpl(DeleteCommandImpl.java:53)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:38)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:17)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.deleteAll(KEntitiesImpl.kt:273)
	at org.babyfish.jimmer.sql.kt.KEntities.deleteAll$default(KEntities.kt:113)
	at org.babyfish.jimmer.sql.kt.KSqlClient.deleteByIds(KSqlClient.kt:230)
	at org.babyfish.jimmer.sql.kt.KSqlClient.deleteByIds$default(KSqlClient.kt:229)
	at top.potmot.service.ModelService.delete$lambda$15(ModelService.kt:138)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at top.potmot.service.ModelService.delete(ModelService.kt:137)
```

**Comment by pot-mot** [comment]
目前排查到的位置是ChildTableOperator:332
![image](https://github.com/user-attachments/assets/ccc4c2ef-874e-4b34-bdda-f835e2ae7eb1)

**Comment by pot-mot** [comment]
ChildTableOperator:334 builder.sql(targetGetter) 连续加入了两次targetGetter
![image](https://github.com/user-attachments/assets/55f91cf3-169e-4ab9-840b-c262b96c62f6)

**Comment by babyfish-ct** [comment]
Try `0.8.162`
