### ISSUE TITLE
[FR]Optimize the position of the select statement for post-facto investigations to avoid confusion

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#657]
# Current Situation
When there is a database error, jimmer tries to try to investigate the cause of the error, so it generates an additional select statement, which then appears first in the log, followed by the user's own sql statement.

# Reproduction Steps
The following code, intentionally book's name as key, intentionally create a violation of the unique constraints of the instance, and then directly use insert.
```java
    @Bean
    public ApplicationRunner applicationRunner(
            @Lazy TransactionTemplate transactionTemplate,
            @Lazy JSqlClient sqlClient
    ) {
        return args -> transactionTemplate.executeWithoutResult(status -> {
            Book book = BookDraft.$.produce(draft -> draft.setName("java").setPrice(100));
            sqlClient.insert(book);
        });
    }
```
After the execution of the log is as follows, you can see that there is a select first, and then insert, which has a little confusing.
```
2024-09-05T19:06:29.529+08:00  INFO 5080 --- [           main] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: COMMAND(INVESTIGATE_CONSTRAINT_VIOLATION_ERROR)
SQL: select
    tb_1_.ID
from BOOK tb_1_
where
    tb_1_.NAME = ? /* java */
JDBC response status: failed<org.babyfish.jimmer.sql.runtime.ExecutionException>
Time cost: 2ms
<===Execute SQL
2024-09-05T19:06:29.529+08:00  INFO 5080 --- [           main] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: COMMAND
SQL: insert into BOOK(NAME, PRICE) values(?, ?)
batch-0: [java, 100.0]
JDBC response status: failed<org.babyfish.jimmer.sql.runtime.ExecutionException>
Time cost: 48ms

2024-09-05T19:06:29.532+08:00  INFO 5080 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-05T19:06:29.547+08:00 ERROR 5080 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.babyfish.jimmer.sql.runtime.ExecutionException: Cannot execute SQL statement: select
    tb_1_.ID
from BOOK tb_1_
where
    tb_1_.NAME = ?, variables: [java]
```

# Expected Behavior
Put this kind of after-the-fact investigation of the select statement, to the end of the log, to reduce such confusion.

**Comment by babyfish-ct** [comment]
Try `0.8.170`

**Comment by kiangti** [comment]
Reproduced the same issue in version `0.9.117`
```log
2025-12-05 11:21:32,147+08  INFO --- [nio-8081-exec-2] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
--- Business related stack trace information ---
com.kc.jimmerdemo.domain.user.UserService.save(UserService.kt:45)
com.kc.jimmerdemo.controller.UserController.create(UserController.kt:65)
Purpose: COMMAND(INVESTIGATE_CONSTRAINT_VIOLATION_ERROR)
SQL: select
    tb_1_.id,
    tb_1_.tenant_id,
    tb_1_.created_at,
    tb_1_.updated_at,
    tb_1_.is_deleted,
    tb_1_.username,
    tb_1_.password,
    tb_1_.age,
    tb_1_.address,
    tb_1_.user_status
from "user" tb_1_
where
        tb_1_.id = '1'
    and
        tb_1_.is_deleted <> 1
JDBC response status: success
Time cost: 16ms
<===Execute SQL
2025-12-05 11:21:32,152+08  INFO --- [nio-8081-exec-2] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
--- Business related stack trace information ---
com.kc.jimmerdemo.domain.user.UserService.save(UserService.kt:45)
com.kc.jimmerdemo.controller.UserController.create(UserController.kt:65)
Purpose: MUTATE
SQL: insert into "user"(id, tenant_id, created_at, updated_at, is_deleted, username, password, age, address, user_status) values('1', '1', '2025-12-05 11:21:32.073497', '2025-12-05 11:21:32.073653', 0, 'lllll', 'fffff', null'DbNull{type=java.lang.Integer}', null'DbNull{type=java.lang.String}', 'ACTIVE')
JDBC response status: failed<org.babyfish.jimmer.sql.exception.SaveException$NotUnique>
Time cost: 68ms
<===Execute SQL
2025-12-05 11:21:32,160+08 ERROR --- [nio-8081-exec-2] c.e.j.i.e.GlobalExceptionHandler         : org.babyfish.jimmer.sql.exception.SaveException$NotUnique: Save error caused by the path: "<root>": Cannot save the entity, the value of the id property "com.kc.jimmerdemo.domain.entity.User.id" is "1" which already exists

org.babyfish.jimmer.sql.exception.SaveException$NotUnique: Save error caused by the path: "<root>": Cannot save the entity, the value of the id property "com.kc.jimmerdemo.domain.entity.User.id" is "1" which already exists
	at org.babyfish.jimmer.sql.ast.impl.mutation.MutationContext.createConflictId(MutationContext.java:276)
	at org.babyfish.jimmer.sql.ast.impl.mutation.EntityInvestigator.translateAll(EntityInvestigator.java:238)
	at org.babyfish.jimmer.sql.ast.impl.mutation.EntityInvestigator.investigate(EntityInvestigator.java:73)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.translateException(Operator.java:887)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.lambda$executeAndGetRowCountsOneByOne$1(Operator.java:706)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:60)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.prettyLog(ExecutorForLog.java:151)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.execute(ExecutorForLog.java:62)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.executeAndGetRowCountsOneByOne(Operator.java:678)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.executeAndGetRowCounts(Operator.java:611)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.execute(Operator.java:859)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.insert(Operator.java:192)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:425)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveAllImpl(Saver.java:141)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:65)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:193)
	at org.babyfish.jimmer.runtime.Internal.lambda$produceList$0(Internal.java:94)
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:122)
	at org.babyfish.jimmer.runtime.Internal.produceList(Internal.java:84)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:61)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:251)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.lambda$execute$0(SimpleEntitySaveCommandImpl.java:215)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:56)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:212)
	at org.babyfish.jimmer.sql.ast.mutation.SimpleEntitySaveCommand.execute(SimpleEntitySaveCommand.java:278)
	at org.babyfish.jimmer.sql.kt.ast.mutation.impl.KSimpleEntitySaveCommandImpl.execute(KSimpleEntitySaveCommandImpl.kt:16)
	at org.babyfish.jimmer.spring.repo.KotlinRepository.save(KotlinRepository.kt:164)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
	at com.kc.jimmerdemo.domain.user.UserRepo$$SpringCGLIB$$0.save(<generated>)
	at com.kc.jimmerdemo.domain.user.UserService.save(UserService.kt:45)
	at com.kc.jimmerdemo.controller.UserController.create(UserController.kt:65)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:250)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:155)
	at org.springframework.web.method.support.InvocableHandlerMethod$KotlinDelegate.invokeFunction(InvocableHandlerMethod.java:335)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:191)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:991)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:896)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:110)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:138)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:165)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:88)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:113)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:83)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:72)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1774)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:973)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:491)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```
