### ISSUE TITLE
重写JRepository的方法但不通过default实现会导致异常

### ISSUE THREAD

**Issue by Guigumua** [babyfish-ct/jimmer#68]
版本: 0.7.35
springboot: 2.7.4

### 异常信息
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimmerDeviceRepository' defined in ****jimmer.JimmerDeviceRepository defined in @EnableJimmerRepositories declared on RicherlinkRichnetAdminApplication: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Illegal abstract spring-data method "public abstract java.util.List ****.BaseJimmerRepository.findAllById(java.lang.Iterable)": This type of property "id" is "long", but the type of parameters[0] of java method is "java.lang.Iterable"
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:936) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at ******Application.main(RicherlinkRichnetAdminApplication.java:14) ~[classes/:na]
Caused by: java.lang.IllegalArgumentException: Illegal abstract spring-data method "public abstract java.util.List ****.BaseJimmerRepository.findAllById(java.lang.Iterable)": This type of property "id" is "long", but the type of parameters[0] of java method is "java.lang.Iterable"
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:74) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:66) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethod.of(QueryMethod.java:34) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.bytecode.MethodCodeWriter.write(MethodCodeWriter.java:38) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.bytecode.ClassCodeWriter.write(ClassCodeWriter.java:113) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.support.JimmerRepositoryFactory.getTargetRepository(JimmerRepositoryFactory.java:100) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:325) ~[spring-data-commons-2.7.3.jar:2.7.3]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[spring-data-commons-2.7.3.jar:2.7.3]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:231) ~[spring-data-commons-2.7.3.jar:2.7.3]
	at org.springframework.data.util.Lazy.get(Lazy.java:115) ~[spring-data-commons-2.7.3.jar:2.7.3]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[spring-data-commons-2.7.3.jar:2.7.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
	... 16 common frames omitted
Caused by: java.lang.IllegalArgumentException: This type of property "id" is "long", but the type of parameters[0] of java method is "java.lang.Iterable"
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.nextParam(QueryMethodParser.java:320) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.resolve(QueryMethodParser.java:258) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.resolve(QueryMethodParser.java:216) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse0(QueryMethodParser.java:88) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
	at org.babyfish.jimmer.spring.repository.parser.QueryMethodParser.parse(QueryMethodParser.java:71) ~[jimmer-spring-boot-starter-0.7.35.jar:na]
```

### 复现

创建一个基类重写`JRepository`
```java
public interface BaseJimmerRepository<E> extends JRepository<E, Long> {
  // 此处重写findAllById, 修改返回类型为List, 但不实现
  @Override
  @NotNull
  List<E> findAllById(@NotNull Iterable<Long> ids);
}
```

### 动机

```java
  @AliasFor("findAllById")
  List<E> findByIds(Iterable<ID> ids);

  @AliasFor("findByIds")
  @NotNull
  default Iterable<E> findAllById(@NotNull Iterable<ID> ids) {
    return this.findByIds(ids);
  }
```

JRepository的源码中, `findAllById`实际调用的`findByIds`, 因此返回类型是`List<E>`, 重写方法期望可以修改返回类型但调用逻辑不变.

另外覆盖其它非`default`的方法也存在同样的问题.

spring-data的一些相关框架是支持这种操作的.

例如`JpaRepository`中多个方法都重写并修改了返回类型
```java
@NoRepositoryBean
public interface JpaRepository<T, ID> extends PagingAndSortingRepository<T, ID>, QueryByExampleExecutor<T> {

	@Override
	List<T> findAll();

	@Override
	List<T> findAll(Sort sort);

	@Override
	List<T> findAllById(Iterable<ID> ids);

	@Override
	<S extends T> List<S> saveAll(Iterable<S> entities);
}
```

### issue 
是否考虑支持子类重写修改返回类型但不实现?

**Comment by babyfish-ct** [comment]
我会把Jimmer接口的返回类型设定为`List<E>`

而这个功能无法支持，用户如果覆盖为`特殊集合框架的列表<E> findAll()`那就完了
