### ISSUE TITLE
There is no reader for unknown type "org.postgresql.util.PGobject"

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#718]
## 版本
Jimmer 0.8.187

## 复现步骤
- Springboot 中整合Jimmer
- 定义 ScalarProvider，用于转换PG数据库中的 inet 类型
```kotlin
@Component
    class InetAddressScalarProvider : ScalarProvider<InetAddress, PGobject> {
        override fun toScalar(sqlValue: PGobject): InetAddress {
            return InetAddress.getByName(sqlValue.value)
        }

        override fun toSql(scalarValue: InetAddress): PGobject {
            val pgObject = PGobject()
            pgObject.type = "inet"
            pgObject.value = scalarValue.hostAddress
            return pgObject
        }
    }
```
实体类定义
```kotlin
@Entity
@Table(name = "sys_user")
interface SystemUser : AbstractEntity, DepartmentAware, LogicalDelete {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long

 //// 其他字段省略

    /**
     * 最后登录IP地址
     */
    val lastLoginIp: InetAddress?

}
```
使用KSqlClient 进行查询时报错
```kotlin
sql.createQuery(SystemUser::class) {
    where(table.username eq username)
    select(table.fetch(SystemUserFetchers.USER_ROLE_PERMISSION_FETCHER))
}.fetchOneOrNull()
```
```
java.lang.IllegalStateException: There is no reader for unknown type "org.postgresql.util.PGobject" in both "org.babyfish.jimmer.sql.runtime.ScalarProvider" and "org.babyfish.jimmer.sql.dialect.PostgresDialect"
	at org.babyfish.jimmer.sql.runtime.ReaderManager.unknownSqlTypeReader(ReaderManager.java:202)
	at org.babyfish.jimmer.sql.runtime.ReaderManager.scalarProviderReader(ReaderManager.java:169)
	at org.babyfish.jimmer.sql.runtime.ReaderManager.scalarReader(ReaderManager.java:117)
	at org.babyfish.jimmer.sql.runtime.ReaderManager.createPropReader(ReaderManager.java:77)
	at org.babyfish.jimmer.impl.util.PropCache.get(PropCache.java:79)
	at org.babyfish.jimmer.sql.runtime.ReaderManager.reader(ReaderManager.java:63)
	at org.babyfish.jimmer.sql.JSqlClientImpl.getReader(JSqlClientImpl.java:749)
	at org.babyfish.jimmer.sql.runtime.Readers.createSingleReader(Readers.java:126)
	at org.babyfish.jimmer.sql.runtime.Readers.createReader(Readers.java:27)
	at org.babyfish.jimmer.sql.runtime.Selectors.lambda$select$1(Selectors.java:41)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor.execute(DefaultExecutor.java:62)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.simpleLog(ExecutorForLog.java:117)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog.execute(ExecutorForLog.java:47)
	at org.babyfish.jimmer.sql.runtime.Selectors.select(Selectors.java:31)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.executeImpl(ConfigurableRootQueryImpl.java:256)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:27)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:246)
	at org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl.execute(ConfigurableRootQueryImpl.java:26)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findByIds(EntitiesImpl.java:330)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:185)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.lambda$findById$3(EntitiesImpl.java:137)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31)
	at org.babyfish.jimmer.sql.ast.impl.EntitiesImpl.findById(EntitiesImpl.java:137)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.findById(KEntitiesImpl.kt:55)
	at org.babyfish.jimmer.sql.kt.KSqlClient.findById(KSqlClient.kt:105)
	at io.elva.wave.core.backend.CoreDebugController.debugJimmer2(CoreDebugController.kt:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at io.elva.wave.core.backend.CoreDebugController$$SpringCGLIB$$0.debugJimmer2(<generated>) [8 skipped]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) [11 skipped]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) [1 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [1 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [69 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [2 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [2 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [2 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) [2 skipped]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1595)

```

**Comment by babyfish-ct** [comment]
Try `0.9.0`
