### ISSUE TITLE
多数据源表名相同时报错

### ISSUE THREAD

**Issue by xia-sc** [babyfish-ct/jimmer#733]
环境:
kotlin
soringboot:3.3.3

在进行新旧数据库数据迁移时,有两张表
表1(数据源1)
```kotlin
@Entity

@Table(name = "care.sys_event_bill")

interface CareSysEventBill {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long

    val code: String?

    @Column(name = "CREATE_DATE_TIME")
    val createDateTime: LocalDateTime?

    @Column(name = "CONTENT")
    val content: String?

    @Column(name = "STATUS")
    val status: String?

    @Column(name = "SOLVE_OPINION")
    val solveOption: String?

    @Column(name = "RECTIFICATION_PROGRAM")
    val rectificationProgram: String?
}

```
表2(数据源2)
```kotlin
@Entity
@Table(name = "itisp.sys_route_bill")
interface SysRouteBill {

    /**
     *  主键
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "route_id")
    val routeId: Long

    /**
     *  编号
     */
    @Column(name = "route_code")
    val routeCode: String?

    /**
     *  状态:完成，执行
     */
    @Column(name = "route_status")
    val routeStatus: String?


    @OneToOne
    @JoinColumn(name = "car_id", referencedColumnName = "car_id")
    val sysCar: SysCar?

    @OneToOne
    @JoinColumn(name = "driver_id", referencedColumnName = "driver_id")
    val sysDriver: SysDriver?

//    @Column(name = "car_id")
//    val carId: Long?

    /**
     *  开始日期
     */
    @Column(name = "start_date_time")
    val startDateTime: LocalDateTime?
}
```
报如下错误

```java

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eventService' defined in file [E:\jetbrains\idea\itisp\data-portability\build\classes\kotlin\main\com\cn\itisp\dataportability\service\EventService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'careSqlClient' defined in class path resource [com/cn/itisp/dataportability/config/SqlClientConfig.class]: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'careSqlClient' threw exception with message: Illegal entity manager, the table "SYS_ROUTE_BILL" is shared by both "com.cn.itisp.dataportability.care.entity.CareSysRouteBill" and "com.cn.itisp.dataportability.itisp.entity.SysRouteBill"
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.12.jar:6.1.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.12.jar:6.1.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.3.jar:3.3.3]
	at com.cn.itisp.dataportability.DataPortabilityApplicationKt.main(DataPortabilityApplication.kt:16) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'careSqlClient' defined in class path resource [com/cn/itisp/dataportability/config/SqlClientConfig.class]: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'careSqlClient' threw exception with message: Illegal entity manager, the table "SYS_ROUTE_BILL" is shared by both "com.cn.itisp.dataportability.care.entity.CareSysRouteBill" and "com.cn.itisp.dataportability.itisp.entity.SysRouteBill"
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.12.jar:6.1.12]
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.babyfish.jimmer.sql.kt.KSqlClient]: Factory method 'careSqlClient' threw exception with message: Illegal entity manager, the table "SYS_ROUTE_BILL" is shared by both "com.cn.itisp.dataportability.care.entity.CareSysRouteBill" and "com.cn.itisp.dataportability.itisp.entity.SysRouteBill"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.12.jar:6.1.12]
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: Illegal entity manager, the table "SYS_ROUTE_BILL" is shared by both "com.cn.itisp.dataportability.care.entity.CareSysRouteBill" and "com.cn.itisp.dataportability.itisp.entity.SysRouteBill"
	at org.babyfish.jimmer.sql.runtime.EntityManager.tableSharedBy(EntityManager.java:439) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager.access$300(EntityManager.java:32) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.createRawTypeMap(EntityManager.java:708) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.createTypeMap(EntityManager.java:624) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.meta.impl.MetaCache.get(MetaCache.java:58) ~[jimmer-core-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager$Data.getTypeMap(EntityManager.java:619) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.runtime.EntityManager.validate(EntityManager.java:397) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.JSqlClientImpl$BuilderImpl.build(JSqlClientImpl.java:1571) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.di.JLazyInitializationSqlClient.sqlClient(JLazyInitializationSqlClient.java:35) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.di.AbstractJSqlClientDelegate.getEntities(AbstractJSqlClientDelegate.java:89) ~[jimmer-sql-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.kt.impl.KSqlClientImpl.<init>(KSqlClientImpl.kt:76) ~[jimmer-sql-kotlin-0.8.186.jar:na]
	at org.babyfish.jimmer.sql.kt.KSqlClientKt.toKSqlClient(KSqlClient.kt:265) ~[jimmer-sql-kotlin-0.8.186.jar:na]
	at org.babyfish.jimmer.spring.SqlClients.kotlin(SqlClients.kt:74) ~[jimmer-spring-boot-starter-0.8.186.jar:na]
	at org.babyfish.jimmer.spring.SqlClients.kotlin(SqlClients.kt:50) ~[jimmer-spring-boot-starter-0.8.186.jar:na]
	at com.cn.itisp.dataportability.config.SqlClientConfig.careSqlClient(SqlClientConfig.kt:25) ~[main/:na]
	at com.cn.itisp.dataportability.config.SqlClientConfig$$SpringCGLIB$$0.CGLIB$careSqlClient$0(<generated>) ~[main/:na]
	at com.cn.itisp.dataportability.config.SqlClientConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.12.jar:6.1.12]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348) ~[spring-context-6.1.12.jar:6.1.12]
	at com.cn.itisp.dataportability.config.SqlClientConfig$$SpringCGLIB$$0.careSqlClient(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.12.jar:6.1.12]
	... 34 common frames omitted
```
请问对于多数据源表名相同时报错,有解决的方法吗(两个库都是独立的)

**Comment by babyfish-ct** [comment]
https://babyfish-ct.github.io/jimmer-doc/zh/docs/configuration/database-validation

**Comment by xia-sc** [comment]
不知道是不是我配置的原因我按照文档设置完后还是有这个错误Caused by: java.lang.IllegalArgumentException: Illegal entity manager, the table "SYS_ROUTE_BILL" is shared by both "com.cn.itisp.dataportability.care.entity.CareSysRouteBill" and "com.cn.itisp.dataportability.itisp.entity.SysRouteBill" 我在另一个表名后面添加了个空格解决了这个问题,正常的查询是没有问题的.😂![微信截图_20241028181831](https://github.com/user-attachments/assets/969995f9-ee98-4b6a-bc3f-2a501f8b86fe)

**Comment by babyfish-ct** [comment]
用错了，这是错误用法。

任何两个类，表名必须不同。一个表不能被重复映射

Jimmer又一个叫触发器的高级功能，数据库变更推送过来，发现很多个类重复映射一张表，直接懵逼
