### ISSUE TITLE
[BUG]在Postgres数据库中，表的主键若是不在Column的第一个位置，Jimmer关联实体Save时执行Batch方法执行无法获取正确的ID

### ISSUE THREAD

**Issue by wushiwoming** [babyfish-ct/jimmer#734]
Postgres中业务表结构如下，id为主键
![image](https://github.com/user-attachments/assets/13319cb9-8568-44ec-a8dc-6c542c4fafbb)
Cannot get generated ids for batch SQL statement: insert into BUSINESS(DESCRIPTION) values(?)
org.babyfish.jimmer.sql.exception.ExecutionException: Cannot get generated ids for batch SQL statement: insert into BUSINESS(DESCRIPTION) values(?)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor$BatchContextImpl.generatedIds(DefaultExecutor.java:267)
	at org.babyfish.jimmer.sql.runtime.ExecutorForLog$Batch.generatedIds(ExecutorForLog.java:275)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.executeAndGetRowCounts(Operator.java:508)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.execute(Operator.java:551)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Operator.insert(Operator.java:135)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveSelf(Saver.java:208)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveAllImpl(Saver.java:107)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.savePreAssociation(Saver.java:161)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.saveAllImpl(Saver.java:98)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.lambda$save$0(Saver.java:48)
	at org.babyfish.jimmer.runtime.Internal.modifyDraft(Internal.java:173)
	at org.babyfish.jimmer.runtime.Internal.lambda$produce$1(Internal.java:42)
	at org.babyfish.jimmer.runtime.Internal.usingDraftContext(Internal.java:102)
	at org.babyfish.jimmer.runtime.Internal.produce(Internal.java:39)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Saver.save(Saver.java:44)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.executeImpl(SimpleEntitySaveCommandImpl.java:47)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:39)
	at org.babyfish.jimmer.sql.ast.impl.mutation.SimpleEntitySaveCommandImpl.execute(SimpleEntitySaveCommandImpl.java:18)
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.save(KEntitiesImpl.kt:205)
	at org.babyfish.jimmer.sql.kt.KEntities.save$default(KEntities.kt:67)
	at org.babyfish.jimmer.sql.kt.KSqlClient.save(KSqlClient.kt:263)
	at com.example.demo.DemoService.create(DemoService.kt:22)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at com.example.demo.DemoService$$SpringCGLIB$$0.create(<generated>)
	at com.example.demo.DemoApplicationTests.testCreate(DemoApplicationTests.kt:26)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.postgresql.util.PSQLException: conversion to class java.lang.Long from varchar not supported
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3789)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getObject(HikariProxyResultSet.java)
	at org.babyfish.jimmer.sql.runtime.DefaultExecutor$BatchContextImpl.generatedIds(DefaultExecutor.java:260)
	... 39 more

![image](https://github.com/user-attachments/assets/4aed5b86-cb73-4608-a32b-89b0138af78c)

**Comment by wushiwoming** [comment]
> 实体和save的代码是什么，我这边测试实体id字段不在第一个，获取自增id时只有id这一个字段

![image](https://github.com/user-attachments/assets/5c9709c4-a920-43d2-ad0d-29e82e104394)
聚合根：Instance
![image](https://github.com/user-attachments/assets/0b4cb50a-2742-4761-b997-b25da31ea63f)
OneToMany关联：Business
![image](https://github.com/user-attachments/assets/b13351c7-9a5e-4e9b-a5f8-f1be77286022)

**Comment by Enaium** [comment]
pgjdbc偷懒，没做这个功能，直接返回所有列
![](https://github.com/user-attachments/assets/3e33db36-a343-498f-a015-fedb3f9448d1)
![](https://github.com/user-attachments/assets/7f5e3ca5-4b75-4fe4-910c-51481a76c219)

**Comment by babyfish-ct** [comment]
Try `0.9.5`
