### ISSUE TITLE
use null(id) in flat() cause  Unable to instantiate `is null` predicate which attempts to check if a non-null property of root table or inner joined table is null

### ISSUE THREAD

**Issue by qifan777** [babyfish-ct/jimmer#735]
```txt
specification PaymentDetailsSpec {
    #allScalars
    associatedIdEq(distributor)
    like/i(batch)
    // works
    null(transferOrder) as transferOrderIsNull
    transferOrder{
        status
    }
// not work
//    flat(transferOrder) {
//        null(id) as transferOrderIsNull
//        status
//    }
}
```
```java
java.lang.IllegalArgumentException: Unable to instantiate `is null` predicate which attempts to check if a non-null property of root table or inner joined table is null (eg: `table.parent().isNull()`). There are two solutions: 1. Use associated id property (eg: `table.parentId().isNull()`), 2. This non-property must belong to a join table and table join path needs to have at least one left join (eg: `table.parent(JoinType.LEFT).isNull()`). The non-null property is `id` of table `org.babyfish.jimmer.meta.impl.ImmutableTypeImpl`.
	at org.babyfish.jimmer.sql.ast.impl.NullityPredicate.<init>(NullityPredicate.java:41)
	at org.babyfish.jimmer.sql.ast.impl.ExpressionImplementor.isNull(ExpressionImplementor.java:65)
	at org.babyfish.jimmer.sql.ast.query.specification.PredicateApplier.isNull(PredicateApplier.java:130)
	at io.github.qifan777.server.order.payment.entity.dto.PaymentDetailsSpec.applyTo(PaymentDetailsSpec.java:200)
	at org.babyfish.jimmer.sql.ast.impl.query.MutableRootQueryImpl.where(MutableRootQueryImpl.java:229)
	at io.github.qifan777.server.order.payment.repository.PaymentDetailsRepository.findPage(PaymentDetailsRepository.java:33)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at 
```

**Comment by babyfish-ct** [comment]
Try `0.9.5`
