### ISSUE TITLE
jimmer实体属性名，首字母大写会导致序列化失败

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#748]
![image](https://github.com/user-attachments/assets/83734995-1b97-44b6-a40b-c6eb0357d7d1)
![image](https://github.com/user-attachments/assets/095bb69b-ee11-4623-8ce8-52968602dd08)

Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: There is no jimmer property for public final java.lang.String org.babyfish.jimmer.sql.example.model.BookDraft$Producer$Implementor.getStoreName()
	at org.babyfish.jimmer.ImmutableObjects.toString(ImmutableObjects.java:365)
	at org.babyfish.jimmer.sql.example.model.BookDraft$Producer$Impl.toString(BookDraft.java:924)
	at java.base/java.lang.String.valueOf(String.java:4507)
	at java.base/java.io.PrintStream.println(PrintStream.java:1187)
	at org.babyfish.jimmer.sql.example.App.main(App.java:34)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: There is no jimmer property for public final java.lang.String org.babyfish.jimmer.sql.example.model.BookDraft$Producer$Implementor.getStoreName()
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1447)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:544)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:822)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at org.babyfish.jimmer.ImmutableObjects.toString(ImmutableObjects.java:363)
	... 4 more

**Comment by babyfish-ct** [comment]
Try `0.9.10`
