### ISSUE TITLE
逻辑删除id定义在父级会抛出异常

### ISSUE THREAD

**Issue by yangwulang** [babyfish-ct/jimmer#80]
```java
@MappedSuperclass
public interface DataTypeBase extends TypeBase {
    /**
     * 删除
     */
    String STATUS_DELETE = "1";
    /**
     * 正常
     */
    String STATUS_NORMAL = "0";

    @NotNull
    @LogicalDeleted(value = STATUS_DELETE, restoredValue = STATUS_NORMAL) //此处产生异常，运行时
    String status();
}

@MappedSuperclass
public interface TypeBase extends Serializable {
    /**
     * 字典类型编码
     * @return 主键值
     */
    @Id
    @NotNull
    String id();
}

```

异常信息
```
Caused by: java.lang.IllegalStateException: Cannot set logical deleted property for type "top.yangwulang.platform.entity.sys.DataTypeBase" because there is an id property in the super type "top.yangwulang.platform.entity.sys.TypeBase"
	at org.babyfish.jimmer.meta.impl.ImmutableTypeImpl$BuilderImpl.logicalDeleted(ImmutableTypeImpl.java:817)
	at top.yangwulang.platform.entity.sys.DataTypeBaseDraft$Producer.<clinit>(DataTypeBaseDraft.java:59)
	... 94 common frames omitted
```

**Comment by babyfish-ct** [comment]
Try 0.7.49

**Comment by babyfish-ct** [comment]
八种基本类型及其包装类型特殊，int/Integer本身表示是否位null，无需@Nullable/@NotNull
