### ISSUE TITLE
Support blank character in Formula sql template

### ISSUE THREAD

**Issue by ForteScarlet** [babyfish-ct/jimmer#805]
Hi. 
When I use `@Formula(sql = "...")`, I get an error if the `sql` contains blank characters: 
```
Caused by: org.babyfish.jimmer.meta.ModelException: Illegal property "xxx.totalThreePhaseVoltage", the formula sql template: Unexpected character ' ' the formula sql "%alias.voltage_phase_a + %alias.voltage_phase_b + %alias.voltage_phase_c"
	at app//org.babyfish.jimmer.meta.impl.ImmutablePropImpl.<init>(ImmutablePropImpl.java:256)
	at app//org.babyfish.jimmer.meta.impl.ImmutableTypeImpl$PropBuilder.build(ImmutableTypeImpl.java:1249)
	at app//org.babyfish.jimmer.meta.impl.ImmutableTypeImpl$BuilderImpl.build(ImmutableTypeImpl.java:1156)
	at app//org.faraday.rs.entity.device.CableDeviceReadingRecordDraft$$.<clinit>(CableDeviceReadingRecordDraft.kt:154)
	... 98 more
```

For example:

```kotlin
@Formula(sql = "%alias.voltage_phase_a + %alias.voltage_phase_b + %alias.voltage_phase_c")
val totalThreePhaseVoltage: BigDecimal
// Error: ModelException
```

When I change out the blank characters in it, the exception is gone.

```kotlin
@Formula(sql = "%alias.voltage_phase_a" +
        "+%alias.voltage_phase_b" +
        "+%alias.voltage_phase_c")
val totalThreePhaseVoltage: BigDecimal
// Is OK
```

**Comment by babyfish-ct** [comment]
Try `0.9.22`
