### ISSUE TITLE
[BUG] - 在使用全局过滤器中使用join关联条件

### ISSUE THREAD

**Issue by zhengchalei** [babyfish-ct/jimmer#826]
### Jimmer Version

0.9.25

### JDK Version

21

### Database

Postgresql

### OS

Windows

### Expected behavior

在 KAssociationIntegrityAssuranceFilter 中, 添加  args.apply { where(table.user.id.eq(currentUserId)) } 出现异常

### Actual behavior

在 KAssociationIntegrityAssuranceFilter 中, 添加  args.apply { where(table.user.id.eq(currentUserId)) } 出现异常

### Description

java.lang.reflect.UndeclaredThrowableException: null
	at jdk.proxy2/jdk.proxy2.$Proxy133.filter(Unknown Source)
	at org.babyfish.jimmer.sql.filter.impl.FilterManager$ExportedFilter.lambda$filter$0(FilterManager.java:848)
	

Caused by: java.lang.IllegalStateException: Table join is disabled because it is not allowed by cacheable filter
	at org.babyfish.jimmer.sql.kt.ast.table.impl.KNonNullTableExImpl.join(KNonNullTableExImpl.kt:50)
	at org.babyfish.jimmer.sql.kt.ast.table.impl.KNonNullTableExImpl.join(KNonNullTableExImpl.kt:21)

### Reproduction steps

额

**Comment by babyfish-ct** [comment]
这不是BUG，全局过滤器禁止join时因为深层次技术原因，如果join不能用，请使用万能的subquery

**Comment by zhengchalei** [comment]
> 这不是BUG，全局过滤器禁止join时因为深层次技术原因，如果join不能用，请使用万能的subquery
> 
> `Table join is disabled because it is not allowed by cacheable filter`

```kotlin
@MappedSuperclass
interface DataScopeAware {

    @ManyToOne @JoinColumn(name = "user_id") val user: SysUser?

    @IdView("user") val userId: Long?

}
```


```kotlin
@Component
class DataScopeFilter(private val jdbcTemplate: JdbcTemplate) : KAssociationIntegrityAssuranceFilter<DataScopeAware> {

    /**
     * 根据当前用户的数据权限过滤查询范围
     *
     * 此函数重写了KFilterArgs<DataScopeAware>接口的filter方法，根据当前用户所属的数据权限类型，
     * 动态修改查询条件，以限制查询结果范围这使得每个用户只能查询自己有权限看到的数据
     *
     * @param args 查询参数对象，包含查询所需的表格信息和条件构建器通过这个参数，我们可以添加额外的查询条件
     */
    override fun filter(args: KFilterArgs<DataScopeAware>) {
        // 获取当前用户的数据权限范围
        val currentUserDataScope = SecurityUtils.getCurrentUserDataScope()

        // 根据不同的数据权限范围，采取不同的过滤策略
        when (currentUserDataScope) {
            // 如果当前用户可以查看所有数据，则不进行任何过滤
            ALL -> return
            // 如果当前用户只能查看自己的数据，获取当前用户的ID，并添加过滤条件
            SELF -> SecurityUtils.getCurrentUserIdOrNull()?.let { currentUserId ->
                args.apply { where(table.user.id eq currentUserId) }
            }
            // 如果当前用户只能查看本部门的数据，获取当前用户的部门ID，并添加过滤条件
            DEPARTMENT -> SecurityUtils.getCurrentUserDepartmentIdOrNull()?.let { currentUserDepartmentId ->
                args.apply { where(table.user.department.id.eq(currentUserDepartmentId)) }
            }
            // 如果当前用户可以查看本部门及子部门的数据，获取当前用户的部门ID，以及所有子部门的ID，并添加过滤条件
            DEPARTMENT_AND_SUB_DEPARTMENT -> SecurityUtils.getCurrentUserDepartmentIdOrNull()
                ?.let { currentUserDepartmentId ->
                    val sql =
                        """
                        WITH RECURSIVE DepartmentHierarchy AS (
                            SELECT id FROM sys_department WHERE id = ?
                            UNION ALL
                            SELECT d.id FROM sys_department d
                            INNER JOIN DepartmentHierarchy dh ON d.parent_id = dh.id
                        )
                        SELECT id FROM DepartmentHierarchy
                    """
                    val childrenIds = this.jdbcTemplate.queryForList(sql, Long::class.java, currentUserDepartmentId)
                    args.apply { where(table.user.department.id valueIn childrenIds) }
                }
            // 如果当前用户的数据权限是自定义的，根据自定义规则获取当前用户的部门，以及该部门有权限访问的数据范围，并添加过滤条件
            CUSTOM -> SecurityUtils.getCurrentUserDepartmentIdOrNull()?.let { currentUserDepartmentId ->
                val list = this.jdbcTemplate.queryForList(
                    "select data_scope_department_id from sys_department_data_scope where department_id = ?",
                    Long::class.java,
                    currentUserDepartmentId
                )
                args.apply { where(table.user.department.id valueIn list) }
            }
        }
    }
}

/**
 * 定义数据可见范围。 此枚举类用于表示用户可以访问的数据范围，不同的枚举值代表不同的数据可见级别。
 *
 * @see EnumType 该注解用于指定持久化枚举类型的策略，使用枚举常量的名称。
 */
@EnumType(EnumType.Strategy.NAME)
enum class DataScope {
    /** 可以访问所有数据。 */
    ALL,

    /** 只能访问自己的数据。 */
    SELF,

    /** 本部门数据权限 */
    DEPARTMENT,

    /** 可以访问子部门的数据。 */
    DEPARTMENT_AND_SUB_DEPARTMENT,

    /** 自定义数据范围。 */
    CUSTOM;

    companion object {
        /**
         * 根据名称获取对应的 DataScope 枚举值。
         *
         * @param name 枚举值的名称
         * @return 对应的 DataScope 枚举值
         * @throws IllegalArgumentException 如果没有找到对应的枚举值
         */
        fun value(name: String): DataScope {
            return entries.find { it.name == name } ?: throw IllegalArgumentException("不存在的数据权限类型: $name")
        }
    }
}
```
这个情况, 如果我有一个实体继承了  DataScopeAware , 这个拦截器的 条件要判断 userId 或者 user.department.id  子查询咋写, 只能知道是过滤集成DataScopeAware类型的实体

**Comment by zhengchalei** [comment]
@babyfish-ct https://github.com/zhengchalei/jimmer-issues-826

**Comment by babyfish-ct** [comment]
join应该基于table，而不是parentTable（那是外部表，不能join）

但是你这个案例下，table无法join（单向关联，@MappedSuperclass也无法定义双向关联）

所以，唯一的办法，利用外键`authorId`，而非连接`author.id`，**事实上，子查询都不需要**

**Comment by zhengchalei** [comment]
> author.id

@babyfish-ct  

要这样写对吗
```kotlin
        args.apply {
           where(
               table.author.id valueIn subQuery(Author::class) {
                   where(table.id eq authorId)
                   select(table.id)
               }
           )
        }
```

如果我有更深层次的, 比如 还要需要判断 table.author.department.id 这时候是不是和 author_id 一个做法, 在冗余一次才可以
