### ISSUE TITLE
[Feature Request] - 根据 ID 更新部分的 Key 时，如果导致了 Key 的冲突，希望能抛出 SaveException.NotUnique 异常

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#832]
### Reason

如标题所示

### Description

假设有如下实体定义：
```kotlin
/**
 * Demo 实体的 Key 由 firstKey 和 secondKey 两个属性构成
 */
@Entity
interface Demo {

    @Id
    val id: Long

    @Key
    val firstKey: String

    @Key
    val secondKey: String
}
``` 
对应于数据库中 `FIRST_KEY` 和 `SECOND_KEY` 列组成的 `UNIQUE` 约束
```sql
create table DEMO
(
    ID         bigint      not null,
    FIRST_KEY  varchar(20) not null,
    SECOND_KEY varchar(20) not null,
    primary key (ID),
    unique key `UK_DEMO` (FIRST_KEY, SECOND_KEY)
);
``` 
根据 ID 更新部分的 Key，代码如下：
```kotlin
@Service
class DemoService(val sqlClient: KSqlClient) {

    /**
     * 根据 ID 更新 firstKey
     */
    fun updateFirstKeyById() {
        sqlClient.update(Demo { 
            id = 1
            firstKey = "newFirstKey"
        })
    }
}
``` 
此时如果导致了 `UNIQUE` 约束的冲突，会抛出原始的 `SQLException`，而不是 Jimmer 包装的 `SaveException.NotUnique` 异常
```
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'newFirstKey-oldSecondKey' for key 'DEMO.UK_DEMO'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:792)
```

**Comment by babyfish-ct** [comment]
Try `0.9.30`
