### ISSUE TITLE
[BUG] "NullPointerException: prop cannot be null" when delete inverse side without mirror mapping

### ISSUE THREAD

**Issue by bingo084** [babyfish-ct/jimmer#844]
### Jimmer Version

0.9.34

### JDK Version

JDK 22

### Database

PostgreSQL

### OS

Linux

### Expected behavior

Delete without error.

### Actual behavior

Null pointer exception occurs when deleting.

### Description

When delete inverse side of many to many relation, if inverse side don't have mirror mapping (ex: `@ManyToMany(mappedBy = "xxx")`), a null pointer exception occurs.

### Reproduction steps

With [jimmer-sql-kt](https://github.com/babyfish-ct/jimmer-examples/tree/main/kotlin/jimmer-sql-kt) of jimmer-examples, delete prop [`books`](https://github.com/babyfish-ct/jimmer-examples/blob/82bfce451fd92e8a7fcea7b28b76db282b69421a/kotlin/jimmer-sql-kt/model/src/main/kotlin/org/babyfish/jimmer/sql/example/kt/model/Author.kt#L26-L27) of `Author.kt`, then run project and delete one author.

### Logs

```java
2024-12-20 17:38:44.887 ERROR 1812508 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: prop cannot be null] with root cause

java.lang.NullPointerException: prop cannot be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	at org.babyfish.jimmer.sql.ast.mutation.AffectedTable$Middle.<init>(AffectedTable.java:71) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.mutation.AffectedTable.of(AffectedTable.java:32) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.AffectedRows.add(AffectedRows.java:21) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.MiddleTableOperator.disconnect(MiddleTableOperator.java:547) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.MiddleTableOperator.disconnect(MiddleTableOperator.java:514) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.execute(Deleter.java:141) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.executeImpl(DeleteCommandImpl.java:55) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31) ~[jimmer-spring-boot-starter-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:40) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:19) ~[jimmer-sql-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.kt.impl.KEntitiesImpl.delete(KEntitiesImpl.kt:252) ~[jimmer-sql-kotlin-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.kt.KEntities.delete$default(KEntities.kt:67) ~[jimmer-sql-kotlin-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.kt.KSqlClient.deleteById(KSqlClient.kt:240) ~[jimmer-sql-kotlin-0.9.34.jar:na]
	at org.babyfish.jimmer.spring.repo.support.AbstractKotlinRepository.deleteById(AbstractKotlinRepository.kt:257) ~[jimmer-spring-boot-starter-0.9.34.jar:na]
	at org.babyfish.jimmer.spring.repo.support.AbstractKotlinRepository$$FastClassBySpringCGLIB$$f8d98053.invoke(<generated>) ~[jimmer-spring-boot-starter-0.9.34.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.babyfish.jimmer.sql.example.kt.repository.AuthorRepository$$EnhancerBySpringCGLIB$$b04819d9.deleteById(<generated>) ~[main/:na]
	at org.babyfish.jimmer.spring.repo.KotlinRepository.deleteById$default(KotlinRepository.kt:246) ~[jimmer-spring-boot-starter-0.9.34.jar:na]
	at org.babyfish.jimmer.sql.example.kt.service.AuthorService.deleteAuthor(AuthorService.kt:64) ~[main/:na]
	at org.babyfish.jimmer.sql.example.kt.service.AuthorService$$FastClassBySpringCGLIB$$620d81c.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.20.jar:5.3.20]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.20.jar:5.3.20]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.20.jar:5.3.20]
	at org.babyfish.jimmer.sql.example.kt.service.AuthorService$$EnhancerBySpringCGLIB$$c9219513.deleteAuthor(<generated>) ~[main/:na]

```

**Comment by babyfish-ct** [comment]
Try `0.9.35`
