### ISSUE TITLE
[BUG] - <title>when define logical delete field on parent class，the logic delete operation not work for associate entities

### ISSUE THREAD

**Issue by qifan777** [babyfish-ct/jimmer#849]
### Jimmer Version

0.9.36

### JDK Version

jdk17

### Database

mysql

### OS

Windows

### Expected behavior

i hope when User is logically deleted，the UserWeChat is also logically deleted too

```java
userRepository.deleteAllById(ids)
```

### Actual behavior

wechat user is physically deleted

### Description

When a user is logically deleted, a wechat user is not logically deleted

### Reproduction steps

```java
userRepository.deleteAllById(ids)
```

### Relation Model

```java
@MappedSuperclass
public interface BaseDateTime {

    LocalDateTime createdTime();

    LocalDateTime editedTime();

    @LogicalDeleted("true")
    boolean isDeleted();
}
```
```java
@Entity
public interface User extends BaseDateTime {

    @Id
    @GeneratedValue(generatorType = UUIDIdGenerator.class)
    String id();

    @Key
    String phone();

    String password()
}
```

```java
@Entity
public interface UserWeChat extends BaseDateTime {

    @Id
    @GeneratedValue(generatorType = UUIDIdGenerator.class)
    String id();

    @Key
    String openId();

    @OnDissociate(DissociateAction.DELETE)
    @OneToOne
    User user();
}
```

### Logs

Save error caused by the path: "<root>.[←creator]": Cannot dissociate child objects because the dissociation action of the many-to-one property "io.github.qifan777.server.ai.role.entity.AiRole.creator" is not configured as "set null" or "cascade". There are two ways to resolve this issue: Decorate the many-to-one property "io.github.qifan777.server.ai.role.entity.AiRole.creator" by @org.babyfish.jimmer.sql.OnDissociate whose argument is `DissociateAction.SET_NULL` or `DissociateAction.DELETE`, or use save command's runtime configuration to override it
	at org.babyfish.jimmer.sql.ast.impl.mutation.MutationContext.throwCannotDissociateTarget(MutationContext.java:215)
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChildTableOperator.disconnect(ChildTableOperator.java:146)
	at org.babyfish.jimmer.sql.ast.impl.mutation.ChildTableOperator.disconnect(ChildTableOperator.java:123)
	at org.babyfish.jimmer.sql.ast.impl.mutation.Deleter.execute(Deleter.java:150)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.executeImpl(DeleteCommandImpl.java:55)
	at org.babyfish.jimmer.spring.cfg.support.SpringConnectionManager.execute(SpringConnectionManager.java:31)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:40)
	at org.babyfish.jimmer.sql.ast.impl.mutation.DeleteCommandImpl.execute(DeleteCommandImpl.java:19)
	at org.babyfish.jimmer.sql.ast.Executable.execute(Executable.java:12)
	at org.babyfish.jimmer.sql.Entities.deleteAll(Entities.java:98)
	at org.babyfish.jimmer.spring.repository.support.JRepositoryImpl.deleteByIds(JRepositoryImpl.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy2/jdk.proxy2.$Proxy181.deleteByIds(Unknown Source)
	at org.babyfish.jimmer.spring.repository.JRepository.deleteAllById(JRepository.java:380)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy2/jdk.proxy2.$Proxy181.deleteAllById(Unknown Source)
	at io.github.qifan777.server.user.root.controller.UserForAdminController.delete(UserForAdminController.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by babyfish-ct** [comment]
Try `0.9.37`
